# Анализ взаимосвязи потребления алкоголя и продолжительности жизни

Этот проект выполнен в учебных целях для демонстрации навыков анализа данных с помощью **Python** и библиотеки **pandas**.

## 🎯 Цель исследования
Изучить, как уровень потребления алкоголя в странах мира связан со средней продолжительностью жизни.

## 📊 Использованные данные
- **drinks.csv** — данные о потреблении алкоголя (Beer, Spirit, Wine, Total)
- **lifeexpectancy-verbose.csv** — данные о средней продолжительности жизни (по странам, полу, годам)

---


# Программирование на Python, БИ

## НИУ ВШЭ, 2025-26 учебный год

### Общая информация

__Дата выдачи:__ 12.10.2025

__Дедлайн:__ 04:00 21.10.2025

### Формат сдачи

### О задании

В данном домашнем задании вы попрактикуетесь в работе с библиотекой Pandas!

In [113]:
import pandas as pd

In [114]:
#from google.colab import drive
#drive.mount('/content/drive')

In [115]:
drinks = pd.read_csv('drinks.csv')
life_exp = pd.read_csv('lifeexpectancy-verbose.csv')

docs!!!!

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.transform.html
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.reset_index.html
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.corr.html
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.pivot_table.html
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.map.html


### 1

В этом домашнем задании вы поработаете с данными исследования зависимости средней продолжительности жизни по странам от количества употребляемого в стране алкоголя.

Вашему вниманию представлено два датасета: `drinks.csv` и `lifeexpectancy-verbose.csv`

Первая таблица содержит в себе сводные данные по количеству употребляемого алкоголя в каждой стране.

Описание датасета:
- `country` —	Name of the country (String)
- `beer_servings`	— Number of beer servings per person in the country (Integer)
- `spirit_servings`	— Number of spirit servings per person in the country (Integer)
- `wine_servings`	— Number of wine servings per person in the country(Integer)
- `total_litres_of_pure_alcohol` —	Total litres of pure alcohol consumed per person in the country (Float)

Вторая таблица содержит в себе информацию о научных статьях и исследованиях о продолжительности жизни (в разных категориях и для разных групп) по той или иной стране.

Откройте в ноутбуке оба файла с данными. Какой размер имеют таблицы? Выведите первые 5 и последние 5 строк для обеих таблиц. Сколько уникальных стран представлено в каждой из таблиц? Сделайте выводы.

In [116]:
# размер таблицы drinks.csv
drinks.shape

(193, 6)

In [117]:
# размер таблицы lifeexpectancy-verbose.csv
life_exp.shape

(6408, 17)

In [118]:
# первые пять строк о научных исследованиях
life_exp.head(5)

index        GhoCode                                       GhoDisplay  \
0      0  WHOSIS_000001                 Life expectancy at birth (years)   
1      1  WHOSIS_000002  Healthy life expectancy (HALE) at birth (years)   
2      2  WHOSIS_000001                 Life expectancy at birth (years)   
3      3  WHOSIS_000001                 Life expectancy at birth (years)   
4      4  WHOSIS_000015                Life expectancy at age 60 (years)   

  PublishStateCode PublishStateDisplay  YearCode  YearDisplay RegionCode  \
0        PUBLISHED           Published      1990         1990        AMR   
1        PUBLISHED           Published      2012         2012        EUR   
2        PUBLISHED           Published      2000         2000        EMR   
3        PUBLISHED           Published      2000         2000        AFR   
4        PUBLISHED           Published      1990         1990       SEAR   

           RegionDisplay WorldBankIncomeGroupGroupCode  \
0               Americas                        WB_LMI   
1                 Europe                         WB_HI   
2  Eastern Mediterranean                         WB_LI   
3                 Africa                        WB_LMI   
4        South_East Asia                        WB_LMI   

  WorldBankIncomeGroupDisplay CountryCode CountryDisplay SexCode  SexDisplay  \
0         Lower_middle_income         NIC      Nicaragua     MLE        Male   
1                 High_income         IRL        Ireland     MLE        Male   
2                  Low_income         YEM          Yemen    BTSX  Both sexes   
3         Lower_middle_income         NGA        Nigeria    FMLE      Female   
4         Lower_middle_income         THA       Thailand    FMLE      Female   

   DisplayValue  Numeric  
0            68     68.0  
1            69     69.3  
2            61     61.0  
3            48     48.0  
4            19     19.0

In [119]:
# последние пять строк о научных исследованиях
life_exp.tail(5)

index        GhoCode                                       GhoDisplay  \
6403   6403  WHOSIS_000001                 Life expectancy at birth (years)   
6404   6404  WHOSIS_000015                Life expectancy at age 60 (years)   
6405   6405  WHOSIS_000001                 Life expectancy at birth (years)   
6406   6406  WHOSIS_000002  Healthy life expectancy (HALE) at birth (years)   
6407   6407  WHOSIS_000001                 Life expectancy at birth (years)   

     PublishStateCode PublishStateDisplay  YearCode  YearDisplay RegionCode  \
6403        PUBLISHED           Published      2000         2000        EMR   
6404        PUBLISHED           Published      1990         1990        WPR   
6405        PUBLISHED           Published      1990         1990        AFR   
6406        PUBLISHED           Published      2012         2012        EUR   
6407        PUBLISHED           Published      2013         2013        EUR   

              RegionDisplay WorldBankIncomeGroupGroupCode  \
6403  Eastern Mediterranean                        WB_LMI   
6404        Western Pacific                        WB_UMI   
6405                 Africa                         WB_LI   
6406                 Europe                        WB_LMI   
6407                 Europe                           NaN   

     WorldBankIncomeGroupDisplay CountryCode CountryDisplay SexCode  \
6403         Lower_middle_income         MAR        Morocco    BTSX   
6404         Upper_middle_income         PLW          Palau    BTSX   
6405                  Low_income         BFA   Burkina Faso    FMLE   
6406         Lower_middle_income         ALB        Albania     MLE   
6407                         NaN         ARM        Armenia    BTSX   

      SexDisplay  DisplayValue   Numeric  
6403  Both sexes            68  68.00000  
6404  Both sexes            16  16.00000  
6405      Female            51  51.00000  
6406        Male            64  63.50000  
6407  Both sexes            71  71.02699

In [120]:
# первые пять строк об употреблении алкоголя
drinks.head(5)

index      country  beer_servings  spirit_servings  wine_servings  \
0      0  Afghanistan              0                0              0   
1      1      Albania             89              132             54   
2      2      Algeria             25                0             14   
3      3      Andorra            245              138            312   
4      4       Angola            217               57             45   

   total_litres_of_pure_alcohol  
0                           0.0  
1                           4.9  
2                           0.7  
3                          12.4  
4                           5.9

In [121]:
# последние пять строк об употреблении алкоголя
drinks.tail(5)

index    country  beer_servings  spirit_servings  wine_servings  \
188    188  Venezuela            333              100              3   
189    189    Vietnam            111                2              1   
190    190      Yemen              6                0              0   
191    191     Zambia             32               19              4   
192    192   Zimbabwe             64               18              4   

     total_litres_of_pure_alcohol  
188                           7.7  
189                           2.0  
190                           0.1  
191                           2.5  
192                           4.7

In [122]:
# количество уникальных стран в drinks.csv
drinks['country'].nunique()

193

In [123]:
# количество уникальных стран в lifeexpectancy-verbose.csv
life_exp['CountryDisplay'].nunique()

194

Странно, одна страна выпускает научные материалы о продолжительности жизни, но по ней нет данных употребления алкоголя. На первый взгляд бросается число - 193, это количество государств-членов ООН.

In [124]:
# теперь найдем страны которых нет во 2 таблице но есть в 1:
life_exp_set = set(life_exp['CountryDisplay'])
drinks_set = set(drinks['country'])
life_exp_set - drinks_set

{'Antigua and Barbuda',
 'Bolivia (Plurinational State of)',
 'Bosnia and Herzegovina',
 'Brunei Darussalam',
 "Côte d'Ivoire",
 "Democratic People's Republic of Korea",
 'Democratic Republic of the Congo',
 'Guinea_Bissau',
 'Iran (Islamic Republic of)',
 "Lao People's Democratic Republic",
 'Micronesia (Federated States of)',
 'Republic of Korea',
 'Republic of Moldova',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Vincent and the Grenadines',
 'Sao Tome and Principe',
 'South Sudan',
 'Syrian Arab Republic',
 'The former Yugoslav republic of Macedonia',
 'Timor_Leste',
 'Trinidad and Tobago',
 'United Kingdom of Great Britain and Northern Ireland',
 'United Republic of Tanzania',
 'United States of America',
 'Venezuela (Bolivarian Republic of)',
 'Viet Nam'}

In [125]:
# а теперь найдем страны которых нет во 1 таблице но есть в 2:
drinks_set - life_exp_set

{'Antigua & Barbuda',
 'Bolivia',
 'Bosnia-Herzegovina',
 'Brunei',
 "Cote d'Ivoire",
 'DR Congo',
 'Guinea-Bissau',
 'Iran',
 'Laos',
 'Macedonia',
 'Micronesia',
 'Moldova',
 'North Korea',
 'Sao Tome & Principe',
 'South Korea',
 'St. Kitts & Nevis',
 'St. Lucia',
 'St. Vincent & the Grenadines',
 'Syria',
 'Tanzania',
 'Timor-Leste',
 'Trinidad & Tobago',
 'USA',
 'United Kingdom',
 'Venezuela',
 'Vietnam'}

Несложно заметить, что наименование стран в этих двух таблицах возможно разное *(Например "USA - Unated States of America" и т. д.)* Несложными ручными сравнениями понимаем, что та самая страна - это Южный Судан ('South Sudan')

То есть в именно этой стране нет данных об употреблении алкогольных напитков, но есть данные о населении, продолжительности жизни и т. д. Возможно, потому что страна достаточно молодая, она образовалась в 2011 году и данных всего навсего не собирались местными органами статистики; также это может быть связано с тем, что данные о потреблении алкоголя в Южном Судане не собираются или недоступны из-за особенностей статистического учёта в стране.

Нельзя исключать, что некоторые страны могут иметь неполные данные по отдельным категориям, что стоит учитывать при последующем анализе.

### 2

Для каждого признака в рассматриваемых данных укажите вид этого признака и кратко обоснуйте, почему вид именно такой.

# **Датасет drinks.csv:**

Признаки:

index - технический, нужен для индексирования строк в таблице, никакого аналитического смысла не представляет

country - категориальный, название страны, неупорядоченное конечное множество

beer_servings - вещественный (числовой), обозначает количество порций пива

spirit_servings - вещественный (числовой), обозначает количество порций крепкого алкогол

wine_servings - вещественный (числовой), обозначает количество порций вин

total_litres_of_pure_alcohol - вещественный, количество литров чистого алкоголя на 1 человека


# **Датасет lifeexpectancy-verbose.csv:**

Признаки:

index - технический, нужен для индексирования строк в таблице, никакого аналитического смысла не представляет

GhoCode	- категориальный, обозначает тип отчета или статистики в ВОЗ, в дальнейшем могут появиться новые типы отчетов, но все равно будет категориальным, так как это уникальные коды учета разных типов отчетов и документов

GhoDisplay - категориальный, текстовое описание показателя, неупорядоченные значения, конечное в данный момент

PublishStateCode - категориальный, различные состояния публикации, ограниченное количество состояний публикации (в этом датасете не обнаружено значений, кроме PUBLISHED, но вероятно возможны варианты DRAFT, RETIRED и т. д.)

PublishStateDisplay	- категориальный, подобный прошлому признаку, но для просмотра не компьютера, а человека (более привычные строчные и большие, меньше правил отображения)

YearCode - порядковый, есть естественный хронологический порядок

YearDisplay	- порядковый, упорядоченные значения годов, но для чтения человека

RegionCode	- категориальный, код региона без числового смысла

RegionDisplay	- категориальный, текстовое название региона (опять же удобный для человека)

WorldBankIncomeGroupGroupCode	- порядковый, уровни дохода государства, согласно данным Всемирного банка, они имеют естественный порядок (от низкого к высокому и прочее), множество конечно

WorldBankIncomeGroupDisplay	- порядковый, текстовое представление предыдущего признака

CountryCode	- категориальный, код страны без чисел, буквенный

CountryDisplay	- категориальный, название стран, в какой-то мере расшифровка кода (предыдущего признака)

SexCode	- категориальный, конечное множество значений (MLE, FMLE, BTSX)

SexDisplay	- категориальный, текстовое описание пола (предыдущего признака)

DisplayValue	- вещественный, значение рассматриваемого показателя в отчете (отброшена дробная часть)

Numeric - вещественный, предыдущее значение в числовом формате (с дробной частью)

### 3

Внимательно изучите признаки обеих таблиц. Как вы считаете, какая из таблиц является главной (а какая сопутствующей)? Почему вы так думаете?

Какой признак может представлять существенный интерес для исследования и являться целевой переменной в рамках представленного датасета? Ответ обоснуйте.

***Бонус (1 бон. балл):*** Попробуйте описать задачу машинного обучения, которую вы могли бы решать для данного датасета с учетом выбранной вами раннее целевой переменной и проблематики исследования. Подробнее про постановку и формализацию задач машинного обучения, а также про различные типы таких задач — вы можете прочитать, например, вот в этой [статье](https://habr.com/ru/company/simbirsoft/blog/565396/) (в начале)

Главной таблицей является таблица lifeexpectancy-verbose.csv, соответственно сопуствующая - drinks.csv. Так как таблица о продолжительности жизни имеет детализированные измерения по годам, полу и различным показателям, а таблица об употреблении алкоголя содержит вспомогательные характеристики по стране, она также в какой-то степени агрегированна. Также наша цель - изучить зависимость продолжительности жизни от некоторых факторов, в частности от уровня употребления алкоголя в стране, поэтому данные о продолжительности жизни - главные, а о уровне употребления алкоголя - дополнительные.

Уже немного сказано в предыдущем абзаце, дополним. Существенный интерес у нас появляется к признаку продолжительность жизни (колонки DisplayValue или Numeric). Этот показатель мы хотим объяснить либо предсказать (это следующий вопрос:)) в том числе с помощью внешних факторов - уровня употребления алкоголя, доходов стран, а также регион и пол.

Теперь поговорим об интересном. Задачей машинного обучения может являться предсказание ожидаемой продолжительности жизни (что очень важно для планирования экономики страны на будущее) от внешних факторов для каждой страны. На вход подается вектор признаков X = [алкоголь, уровень доходов, пол, год], на выходе получаем значение Y - продолжительность жизни.

### 4

Какова доля статей о продолжительности жизни в Африке? Какова доля статей о продолжительности жизни мужчин и доля статей о продолжительности жизни женщин среди всех статей по Африке?

***Бонус (2 бон. балла):*** Сравните эти доли с аналогичными долями по другим регионам. Как вы можете объяснить возникающие сходства и различия? Прокомментируйте полученные результаты.

In [126]:
# доля статей о продолжительности жизни в Африке
life_exp[life_exp['RegionDisplay'] == 'Africa'].shape[0] / life_exp.shape[0]

0.23782771535580524

In [127]:
# количество статей о продолжительности жизни в Африке
cnt_africa = life_exp[life_exp['RegionDisplay'] == 'Africa'].shape[0]
cnt_africa

1524

In [128]:
# доля статей о продолжительности жизни мужчин в Африке от всех статей
cnt_africa_male = life_exp[(life_exp['RegionDisplay'] == 'Africa') & (life_exp['SexDisplay'] == 'Male')].shape[0]
cnt_africa_male / cnt_africa

0.3333333333333333

In [129]:
# доля статей о продолжительности жизни женщин в Африке от всех статей
cnt_africa_female = life_exp[(life_exp['RegionDisplay'] == 'Africa') & (life_exp['SexDisplay'] == 'Female')].shape[0]
cnt_africa_female / cnt_africa

0.3333333333333333

Оказалось, что сумма долей по мужчинам и женщинам не равна 1. При внимательном рассмотрении таблицы мы видим, что в колонке SexDisplay встречаются три значения: Female, Male и Both sexes. Статьи со значением Both sexes отражают статьи для обоих полов, поэтому их нужно учитывать при рассчете долей для обеих групп. Для анализа можно либо учитывать статьи для обоих полов в долях мужчин и женщин, а можно отдельно посчитать долю статей для обоих полов

In [130]:
# доля статей с обоими полами в Африке от всех статей
cnt_africa_both = life_exp[(life_exp['RegionDisplay'] == 'Africa') & (life_exp['SexDisplay'] == 'Both sexes')].shape[0]
cnt_africa_both / cnt_africa

0.3333333333333333

Да, теперь в сумме получается 1. Значит мы коррекно вывели доли для каждых вариантов значений колонки пола. Все эти доли равны, поэтому делаем небезосновательное предположение (на основе арифметики), что при учете статей с обоими полами доля мужчин и женщин - 1 к 1. Проверим с помощью кода.

In [131]:
# доля статей где упоминаются мужчины:
(cnt_africa_male + cnt_africa_both) / (cnt_africa + cnt_africa_both)

0.5

In [132]:
# доля статей где упоминаются женщины:
(cnt_africa_female + cnt_africa_both) / (cnt_africa + cnt_africa_both)

0.5

Теперь посмотрим по другим регионам:

Европа:

In [133]:
# доля статей о продолжительности жизни в Европе
life_exp[(life_exp['RegionDisplay'] == 'Europe')].shape[0] / life_exp.shape[0]

0.272940074906367

In [134]:
# количество статей о продолжительности жизни в Европе
cnt_europe = life_exp[life_exp['RegionDisplay'] == 'Europe'].shape[0]
cnt_europe

1749

In [135]:
# доля статей о продолжительности жизни женщин в Европе от всех статей
cnt_europe_female = life_exp[(life_exp['RegionDisplay'] == 'Europe') & (life_exp['SexDisplay'] == 'Female')].shape[0]
cnt_europe_female / cnt_europe

0.3333333333333333

In [136]:
# доля статей о продолжительности жизни мужчин в Европе от всех статей
cnt_europe_male = life_exp[(life_exp['RegionDisplay'] == 'Europe') & (life_exp['SexDisplay'] == 'Male')].shape[0]
cnt_europe_male / cnt_europe

0.3333333333333333

In [137]:
# доля статей с обоими полами в Европе от всех статей
cnt_europe_both = life_exp[(life_exp['RegionDisplay'] == 'Europe') & (life_exp['SexDisplay'] == 'Both sexes')].shape[0]
cnt_europe_both / cnt_europe

0.3333333333333333

In [138]:
# доля статей где упоминаются женщины:
(cnt_europe_female + cnt_europe_both) / (cnt_europe + cnt_europe_both)

0.5

In [139]:
# доля статей где упоминаются мужчины:
(cnt_europe_male + cnt_europe_both) / (cnt_europe + cnt_europe_both)

0.5

Количество совпадает точь-в-точь. Посмотрим на регион Western Pacific

In [140]:
# доля статей о продолжительности жизни в Западно-Тихоокеанском регионе
life_exp[life_exp['RegionDisplay'] == 'Western Pacific'].shape[0] / life_exp.shape[0]

0.13904494382022473

In [141]:
# количество статей о продолжительности жизни в Западно-Тихоокеанском регионе
cnt_west_pacific = life_exp[life_exp['RegionDisplay'] == 'Western Pacific'].shape[0]
cnt_west_pacific

891

In [142]:
# доля статей о продолжительности жизни женщин в Западно-Тихоокеанском регионе от всех статей
cnt_west_pacific_female = life_exp[(life_exp['RegionDisplay'] == 'Western Pacific') & (life_exp['SexDisplay'] == 'Female')].shape[0]
cnt_west_pacific_female / cnt_west_pacific

0.3333333333333333

In [143]:
# доля статей о продолжительности жизни мужчин в Западно-Тихоокеанском регионе от всех статей
cnt_west_pacific_male = life_exp[(life_exp['RegionDisplay'] == 'Western Pacific') & (life_exp['SexDisplay'] == 'Male')].shape[0]
cnt_west_pacific_male / cnt_west_pacific

0.3333333333333333

In [144]:
# доля статей с обоими полами в Западно-Тихоокеанском регионе от всех статей
cnt_west_pacific_both = life_exp[(life_exp['RegionDisplay'] == 'Western Pacific') & (life_exp['SexDisplay'] == 'Both sexes')].shape[0]
cnt_west_pacific_both / cnt_west_pacific

0.3333333333333333

In [145]:
# доля статей где упоминаются женщины:
(cnt_west_pacific_female + cnt_west_pacific_both) / (cnt_west_pacific + cnt_west_pacific_both)

0.5

In [146]:
# доля статей где упоминаются мужчины:
(cnt_west_pacific_male + cnt_west_pacific_both) / (cnt_west_pacific + cnt_west_pacific_both)

0.5

Что в итоге? Аналогичные доли наблюдаются и в других регионах. Это объясняется тем, что структура отчётных данных ВОЗ единообразна: для каждого показателя публикуются сведения по трём категориям пола — Male, Female и Both sexes. Поэтому распределение по полу остаётся одинаковым для всех регионов и не отражает фактических различий, а лишь стандартизированную схему представления данных.

In [147]:
life_exp.groupby('RegionDisplay')['CountryDisplay'].nunique()

RegionDisplay
Africa                   47
Americas                 35
Eastern Mediterranean    22
Europe                   53
South_East Asia          11
Western Pacific          27
Name: CountryDisplay, dtype: int64

Различия в долях регионов объясняются разным количеством стран, входящих в каждый регион ВОЗ. Европа и Африка включают больше государств, поэтому на них приходится больше записей в датасете. Западно-Тихоокеанский регион содержит меньше стран, что приводит к меньшей доле статей.

### 5

Сколько всего существует видов статей с точки зрения оцениваемого параметра продолжительности жизни? Какой из этих видов статей самый популярный (написано наибольшее количество научных работ)? В рамках найденного вами самого популярного вида статей проведите сравнение, относительно какой из половых групп: мужчины, женщины или же оба пола — статей в нем было больше всего?

In [148]:
# виды статей через столбик GhoDisplay
life_exp['GhoDisplay'].unique()

array(['Life expectancy at birth (years)',
       'Healthy life expectancy (HALE) at birth (years)',
       'Life expectancy at age 60 (years)'], dtype=object)

In [149]:
# их количество через столбик GhoDisplay
life_exp['GhoDisplay'].nunique()

3

In [150]:
# виды статей через столбик GhoCode
life_exp['GhoCode'].unique()

array(['WHOSIS_000001', 'WHOSIS_000002', 'WHOSIS_000015'], dtype=object)

In [151]:
# их количество через столбик GhoCode
life_exp['GhoCode'].nunique()

3

In [152]:
# количество статей на каждую категорию
life_exp['GhoDisplay'].value_counts()

GhoDisplay
Life expectancy at birth (years)                   2328
Life expectancy at age 60 (years)                  2328
Healthy life expectancy (HALE) at birth (years)    1752
Name: count, dtype: int64

Самыми популярными оказались статьи Life expectancy at birth (years)	2328 строк и Life expectancy at age 60 (years) - тоже 2328 строк

In [153]:
# статьи Life expectancy at birth (years) о мужчинах
life_exp[(life_exp['GhoDisplay'] == 'Life expectancy at birth (years)') & (life_exp['SexDisplay'] == 'Male')].shape[0]

776

In [154]:
# статьи Life expectancy at birth (years) о женщинах
life_exp[(life_exp['GhoDisplay'] == 'Life expectancy at birth (years)') & (life_exp['SexDisplay'] == 'Female')].shape[0]

776

In [155]:
# статьи Life expectancy at birth (years) о обоих полов
life_exp[(life_exp['GhoDisplay'] == 'Life expectancy at birth (years)') & (life_exp['SexDisplay'] == 'Both sexes')].shape[0]

776

In [156]:
# статьи Life expectancy at age 60 (years) о мужчинах
life_exp[(life_exp['GhoDisplay'] == 'Life expectancy at age 60 (years)') & (life_exp['SexDisplay'] == 'Male')].shape[0]

776

In [157]:
# статьи Life expectancy at age 60 (years) о женщинах
life_exp[(life_exp['GhoDisplay'] == 'Life expectancy at age 60 (years)') & (life_exp['SexDisplay'] == 'Female')].shape[0]

776

In [158]:
# статьи Life expectancy at age 60 (years) об обоих полах
life_exp[(life_exp['GhoDisplay'] == 'Life expectancy at age 60 (years)') & (life_exp['SexDisplay'] == 'Both sexes')].shape[0]

776

Самыми популярными оказались статьи по показателям Life expectancy at birth (years) и Life expectancy at age 60 (years), при этом их количество одинаковое — по 2328 записей каждая. Если смотреть на распределение по полу в рамках выбранного показателя, то для мужчин, женщин и обоих полов статьи тоже распределены одинаково — по 776 записей на каждую категорию. Это объясняется тем, что структура таблицы ВОЗ стандартизирована: для каждого показателя публикуются данные по всем трём категориям пола. Поэтому здесь мы видим равномерное распределение по полу, а реальные различия между полами из этих данных не прослеживаются.

### 6

Выведите минимальную, среднюю, медианную и максимальную оцененную продолжительность жизни людей от рождения (`life expectancy at birth`). Выберите любые три страны на ваш вкус и проделайте то же самое только для статей по этим странам. Что можно сказать на основе результатов, которые вы получили?

In [159]:
# минимальная, средняя, медианная, максимальная оцененная продолжительность жизни отчетов Life expectancy at birth (years)
life_birth = life_exp[life_exp['GhoCode'] == 'WHOSIS_000001']
life_birth['Numeric'].min(), life_birth['Numeric'].mean(), life_birth['Numeric'].median(), life_birth['Numeric'].max()

(38.0, np.float64(68.44137943298968), 70.857895, 87.15457)

In [160]:
# Для Японии:
life_birth = life_exp[(life_exp[('GhoCode')] == 'WHOSIS_000001') & (life_exp['CountryDisplay'] == 'Japan')]
life_birth['Numeric'].min(), life_birth['Numeric'].mean(), life_birth['Numeric'].median(), life_birth['Numeric'].max()

(76.0, np.float64(81.92561), 81.5, 87.15457)

In [161]:
# Для Ниегрии:
life_birth = life_exp[(life_exp[('GhoCode')] == 'WHOSIS_000001') & (life_exp['CountryDisplay'] == 'Nigeria')]
life_birth['Numeric'].min(), life_birth['Numeric'].mean(), life_birth['Numeric'].median(), life_birth['Numeric'].max()

(45.0, np.float64(50.47333750000001), 50.5, 55.40039)

In [162]:
# Для Бразилии:
life_birth = life_exp[(life_exp[('GhoCode')] == 'WHOSIS_000001') & (life_exp['CountryDisplay'] == 'Brazil')]
life_birth['Numeric'].min(), life_birth['Numeric'].mean(), life_birth['Numeric'].median(), life_birth['Numeric'].max()

(63.0, np.float64(71.46481583333333), 71.305075, 78.79631)

In [163]:
# Для России:
life_birth = life_exp[(life_exp[('GhoCode')] == 'WHOSIS_000001') & (life_exp['CountryDisplay'] == 'Russian Federation')]
life_birth['Numeric'].min(), life_birth['Numeric'].mean(), life_birth['Numeric'].median(), life_birth['Numeric'].max()

(59.0, np.float64(68.07878416666667), 69.0, 75.22597)

Из этих данных видно, что между странами существуют значительные различия в продолжительности жизни. В странах с развитой медициной и высоким уровнем жизни (например, Япония) люди живут значительно дольше, чем в странах с низким уровнем жизни или высоким уровнем заболеваний (например, Нигерия). Бразилия показывает промежуточные значения, что отражает смешанный уровень экономического и социального развития.

### 7

Сформируйте результирующий датафрейм на основе проделанных вами действий в предыдущем номере. У датафрейма должно быть 4 столбца, в соответствии с заданными агреггирующими функциями: минимум, среднее, медиана, максимум, — а также 4 строки: статистика по всему датасету; статистика по трем выбранным вами странам. Сохраните программно созданный вами датафрейм в виде csv файла.

*Примечание. Датафрейм необходимо создавать автоматизированным образом. Не допускается ручной перенос значений из полученных в предыдущем задании ячеек в пустой датафрейм и/или прописывание конкретных значений (чисел) в коде программы. Представьте, что у нас не 3 страны, а 100 и не 4 агреггирующих метрики, а 100!*

In [164]:
result_life_birth = life_exp[life_exp['GhoCode'] == 'WHOSIS_000001']
countries = ['Japan', 'Nigeria', 'Brazil']
country_info = result_life_birth[result_life_birth['CountryDisplay'].isin(countries)].groupby('CountryDisplay')['Numeric'].agg(минимальное='min', среднее='mean', медиана='median', максимальное='max')
world_stats = result_life_birth['Numeric'].agg(минимальное='min', среднее='mean', медиана='median', максимальное='max').to_frame().T
world_stats.index = ['World']
agg_df = pd.concat([world_stats, country_info])
agg_df.to_csv('life_expectancy_summary.csv')
agg_df

минимальное    среднее    медиана  максимальное
World           38.0  68.441379  70.857895      87.15457
Brazil          63.0  71.464816  71.305075      78.79631
Japan           76.0  81.925610  81.500000      87.15457
Nigeria         45.0  50.473338  50.500000      55.40039

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.to_frame.html

### 8

Есть ли в наших датасетах пропуски? Если да, то в каких столбцах? Сколько пропусков в каждом из них?

Подумайте, как стоит избавиться от пропусков в каждом из столбцов, и сделайте это. Аргументируйте ваши действия.

Проверьте, что пропусков нигде не осталось.

*Примечание. Не забудьте сохранить все изменения! В последующих заданиях вы должны работать с уже обновленными датасетами.*

In [165]:
# количество пропусков в таблице drinks.csv
drinks.isna().sum()

index                           0
country                         0
beer_servings                   0
spirit_servings                 0
wine_servings                   0
total_litres_of_pure_alcohol    0
dtype: int64

In [166]:
# количество пропусков в таблице lifeexpectancy-verbose.csv
life_exp.isna().sum()

index                               0
GhoCode                             0
GhoDisplay                          0
PublishStateCode                    0
PublishStateDisplay                 0
YearCode                            0
YearDisplay                         0
RegionCode                          0
RegionDisplay                       0
WorldBankIncomeGroupGroupCode    1164
WorldBankIncomeGroupDisplay      1164
CountryCode                         0
CountryDisplay                      0
SexCode                             0
SexDisplay                          0
DisplayValue                        0
Numeric                             0
dtype: int64

In [167]:
# количество пропусков в таблице life_expectancy_summary.csv
agg_df.isna().sum()

минимальное     0
среднее         0
медиана         0
максимальное    0
dtype: int64

Пропуски данных наблюдаются в таблице lifeexpectancy-verbose.csv в колонках WorldBankIncomeGroupGroupCode	- 1164 пропуска и
WorldBankIncomeGroupDisplay - также 1164 пропуска

In [168]:
# количество пропусков по регионам в таблице lifeexpectancy-verbose.csv
life_exp['WorldBankIncomeGroupGroupCode'].isna().groupby(life_exp['RegionDisplay']).sum()

RegionDisplay
Africa                   282
Americas                 210
Eastern Mediterranean    126
Europe                   318
South_East Asia           66
Western Pacific          162
Name: WorldBankIncomeGroupGroupCode, dtype: int64

In [169]:
life_exp['WorldBankIncomeGroupDisplay'].isna().groupby(life_exp['RegionDisplay']).sum()

RegionDisplay
Africa                   282
Americas                 210
Eastern Mediterranean    126
Europe                   318
South_East Asia           66
Western Pacific          162
Name: WorldBankIncomeGroupDisplay, dtype: int64

In [170]:
# всего записей
life_exp.shape[0]

6408

In [171]:
# доля пропусков
life_exp.isna().sum() / life_exp.shape[0]

index                            0.000000
GhoCode                          0.000000
GhoDisplay                       0.000000
PublishStateCode                 0.000000
PublishStateDisplay              0.000000
YearCode                         0.000000
YearDisplay                      0.000000
RegionCode                       0.000000
RegionDisplay                    0.000000
WorldBankIncomeGroupGroupCode    0.181648
WorldBankIncomeGroupDisplay      0.181648
CountryCode                      0.000000
CountryDisplay                   0.000000
SexCode                          0.000000
SexDisplay                       0.000000
DisplayValue                     0.000000
Numeric                          0.000000
dtype: float64

In [172]:
# количество пропусков по годам в таблице lifeexpectancy-verbose.csv
life_exp['WorldBankIncomeGroupGroupCode'].isna().groupby(life_exp['YearDisplay']).sum()

YearDisplay
1990       0
2000       0
2012       0
2013    1164
Name: WorldBankIncomeGroupGroupCode, dtype: int64

То есть у нас нет данных по 1164 странам за 2013 год, попробуем найти датасеты на сторонних источниках. Нашли данные Всемирного банка (в нашем изначальном датасете - информация тоже из Всемирного банка https://ourworldindata.org/grapher/world-bank-income-groups?tab=table&time=2013&overlay=download-data) Классификация идентична: Low income -> Lower middle income -> Upper middle income -> High income, пэтому можем сделать замену

Мержим по коду страны (так как названия могут отличаться по написанию), также приводим путем преобразований, словарей и метода map() к единым значениям, существовавшим в нашем датасете

In [173]:
ext_src = pd.read_csv('external_source.csv')
life_exp = pd.read_csv('lifeexpectancy-verbose.csv')
dict_display = {'WB_HI':'High_income',
             'WB_LMI':'Lower_middle_income',
             'WB_UMI':'Upper_middle_income',
             'WB_LI':'Low_income'}

dict_code = {'High-income countries':'WB_HI',
             'Lower-middle-income countries':'WB_LMI',
             'Upper-middle-income countries':'WB_UMI',
             'Low-income countries':'WB_LI'}

In [174]:
ext_src.columns = ['CountryDisplay', 'CountryCode', 'YearCode', 'WorldBankIncomeGroupGroupCode']

ext_src = ext_src[ext_src['YearCode'] == 2013]
ext_src['WorldBankIncomeGroupGroupCode'] = ext_src['WorldBankIncomeGroupGroupCode'].map(dict_code)


life_exp = life_exp.merge(
    ext_src[['CountryCode', 'WorldBankIncomeGroupGroupCode']],
    on='CountryCode',
    how='left',
    suffixes=('', '_new')
)

life_exp

index        GhoCode                                       GhoDisplay  \
0         0  WHOSIS_000001                 Life expectancy at birth (years)   
1         1  WHOSIS_000002  Healthy life expectancy (HALE) at birth (years)   
2         2  WHOSIS_000001                 Life expectancy at birth (years)   
3         3  WHOSIS_000001                 Life expectancy at birth (years)   
4         4  WHOSIS_000015                Life expectancy at age 60 (years)   
...     ...            ...                                              ...   
6403   6403  WHOSIS_000001                 Life expectancy at birth (years)   
6404   6404  WHOSIS_000015                Life expectancy at age 60 (years)   
6405   6405  WHOSIS_000001                 Life expectancy at birth (years)   
6406   6406  WHOSIS_000002  Healthy life expectancy (HALE) at birth (years)   
6407   6407  WHOSIS_000001                 Life expectancy at birth (years)   

     PublishStateCode PublishStateDisplay  YearCode  YearDisplay RegionCode  \
0           PUBLISHED           Published      1990         1990        AMR   
1           PUBLISHED           Published      2012         2012        EUR   
2           PUBLISHED           Published      2000         2000        EMR   
3           PUBLISHED           Published      2000         2000        AFR   
4           PUBLISHED           Published      1990         1990       SEAR   
...               ...                 ...       ...          ...        ...   
6403        PUBLISHED           Published      2000         2000        EMR   
6404        PUBLISHED           Published      1990         1990        WPR   
6405        PUBLISHED           Published      1990         1990        AFR   
6406        PUBLISHED           Published      2012         2012        EUR   
6407        PUBLISHED           Published      2013         2013        EUR   

              RegionDisplay WorldBankIncomeGroupGroupCode  \
0                  Americas                        WB_LMI   
1                    Europe                         WB_HI   
2     Eastern Mediterranean                         WB_LI   
3                    Africa                        WB_LMI   
4           South_East Asia                        WB_LMI   
...                     ...                           ...   
6403  Eastern Mediterranean                        WB_LMI   
6404        Western Pacific                        WB_UMI   
6405                 Africa                         WB_LI   
6406                 Europe                        WB_LMI   
6407                 Europe                           NaN   

     WorldBankIncomeGroupDisplay CountryCode CountryDisplay SexCode  \
0            Lower_middle_income         NIC      Nicaragua     MLE   
1                    High_income         IRL        Ireland     MLE   
2                     Low_income         YEM          Yemen    BTSX   
3            Lower_middle_income         NGA        Nigeria    FMLE   
4            Lower_middle_income         THA       Thailand    FMLE   
...                          ...         ...            ...     ...   
6403         Lower_middle_income         MAR        Morocco    BTSX   
6404         Upper_middle_income         PLW          Palau    BTSX   
6405                  Low_income         BFA   Burkina Faso    FMLE   
6406         Lower_middle_income         ALB        Albania     MLE   
6407                         NaN         ARM        Armenia    BTSX   

      SexDisplay  DisplayValue   Numeric WorldBankIncomeGroupGroupCode_new  
0           Male            68  68.00000                            WB_LMI  
1           Male            69  69.30000                             WB_HI  
2     Both sexes            61  61.00000                            WB_LMI  
3         Female            48  48.00000                            WB_LMI  
4         Female            19  19.00000                            WB_UMI  
...          ...           ...       ...                    

Смержили, но надо дополнительно удалить колонку WorldBankIncomeGroupGroupCode_new, которую создавали для удобства

In [175]:
life_exp['WorldBankIncomeGroupGroupCode'] = life_exp['WorldBankIncomeGroupGroupCode'].fillna(life_exp['WorldBankIncomeGroupGroupCode_new'])
life_exp['WorldBankIncomeGroupDisplay'] = life_exp['WorldBankIncomeGroupDisplay'].fillna(life_exp['WorldBankIncomeGroupGroupCode_new'])
life_exp['WorldBankIncomeGroupDisplay'] = life_exp['WorldBankIncomeGroupGroupCode'].map(dict_display)
life_exp.drop(columns=['WorldBankIncomeGroupGroupCode_new'], inplace=True)

У нас получился дополненный датасет:

In [176]:
life_exp

index        GhoCode                                       GhoDisplay  \
0         0  WHOSIS_000001                 Life expectancy at birth (years)   
1         1  WHOSIS_000002  Healthy life expectancy (HALE) at birth (years)   
2         2  WHOSIS_000001                 Life expectancy at birth (years)   
3         3  WHOSIS_000001                 Life expectancy at birth (years)   
4         4  WHOSIS_000015                Life expectancy at age 60 (years)   
...     ...            ...                                              ...   
6403   6403  WHOSIS_000001                 Life expectancy at birth (years)   
6404   6404  WHOSIS_000015                Life expectancy at age 60 (years)   
6405   6405  WHOSIS_000001                 Life expectancy at birth (years)   
6406   6406  WHOSIS_000002  Healthy life expectancy (HALE) at birth (years)   
6407   6407  WHOSIS_000001                 Life expectancy at birth (years)   

     PublishStateCode PublishStateDisplay  YearCode  YearDisplay RegionCode  \
0           PUBLISHED           Published      1990         1990        AMR   
1           PUBLISHED           Published      2012         2012        EUR   
2           PUBLISHED           Published      2000         2000        EMR   
3           PUBLISHED           Published      2000         2000        AFR   
4           PUBLISHED           Published      1990         1990       SEAR   
...               ...                 ...       ...          ...        ...   
6403        PUBLISHED           Published      2000         2000        EMR   
6404        PUBLISHED           Published      1990         1990        WPR   
6405        PUBLISHED           Published      1990         1990        AFR   
6406        PUBLISHED           Published      2012         2012        EUR   
6407        PUBLISHED           Published      2013         2013        EUR   

              RegionDisplay WorldBankIncomeGroupGroupCode  \
0                  Americas                        WB_LMI   
1                    Europe                         WB_HI   
2     Eastern Mediterranean                         WB_LI   
3                    Africa                        WB_LMI   
4           South_East Asia                        WB_LMI   
...                     ...                           ...   
6403  Eastern Mediterranean                        WB_LMI   
6404        Western Pacific                        WB_UMI   
6405                 Africa                         WB_LI   
6406                 Europe                        WB_LMI   
6407                 Europe                        WB_LMI   

     WorldBankIncomeGroupDisplay CountryCode CountryDisplay SexCode  \
0            Lower_middle_income         NIC      Nicaragua     MLE   
1                    High_income         IRL        Ireland     MLE   
2                     Low_income         YEM          Yemen    BTSX   
3            Lower_middle_income         NGA        Nigeria    FMLE   
4            Lower_middle_income         THA       Thailand    FMLE   
...                          ...         ...            ...     ...   
6403         Lower_middle_income         MAR        Morocco    BTSX   
6404         Upper_middle_income         PLW          Palau    BTSX   
6405                  Low_income         BFA   Burkina Faso    FMLE   
6406         Lower_middle_income         ALB        Albania     MLE   
6407         Lower_middle_income         ARM        Armenia    BTSX   

      SexDisplay  DisplayValue   Numeric  
0           Male            68  68.00000  
1           Male            69  69.30000  
2     Both sexes            61  61.00000  
3         Female            48  48.00000  
4         Female            19  19.00000  
...          ...           ...       ...  
6403  Both sexes            68  68.00000  
6404  Both sexes            16  16.00000  
6405      Female            51  51.00000  
6406        Male            64  63.50000  
6407  Both sexes            71  71.02699  

[6408

Проверим сколько теперь пропусков:

In [177]:
life_exp['WorldBankIncomeGroupDisplay'].isna().groupby(life_exp['RegionDisplay']).sum()

RegionDisplay
Africa                    0
Americas                  0
Eastern Mediterranean     0
Europe                    0
South_East Asia           0
Western Pacific          18
Name: WorldBankIncomeGroupDisplay, dtype: int64

Их стало достаточно мало, выводим страны, у которых отсутствует показатели от Всемирного банка (WorldBankIncomeGroupDisplay и WorldBankIncomeGroupGroupCode)

In [178]:
missing_income = life_exp[life_exp['WorldBankIncomeGroupDisplay'].isna()][['CountryDisplay', 'WorldBankIncomeGroupDisplay', 'WorldBankIncomeGroupGroupCode']]
missing_income.drop_duplicates()

CountryDisplay WorldBankIncomeGroupDisplay WorldBankIncomeGroupGroupCode
19            Niue                         NaN                           NaN
98    Cook Islands                         NaN                           NaN
853          Nauru                         NaN                           NaN

У нас осталось 3 страны, для которых данных по доходам за 2013 год нет. Во внешнем датасете external_source.csv для страны Nauru данные есть только с 2015 года, для Cook Islands и Niue данных вовсе нет.

Изучив, как вычисляется классификация Всемирного банка для стран, нашли что она зависит от показателя "gross national income (GNI) per capita". Каждый финансовый год (FY) границы Low income -> Lower middle income -> Upper middle income -> High income пересматриваются  с учётом инфляции и обменного курса доллара США. На время 2013 года показатели были такие:

Низкий доход (Low income): $1,035 или меньше

Нижний средний доход (Lower middle income): от $1,036 до $4,085

Верхний средний доход (Upper middle income): от $4,086 до $12,615

Высокий доход (High income): $12,616 или больше

(Источник https://www.childrenpalliativecarecongress.org/congress-2014/wp-content/uploads/2013/09/World-Bank-List-of-Economies-2013.pdf, последняя страница)

Для Nauru GNI per capita составляет 11 340 долларов США согласно https://www.macrotrends.net/global-metrics/countries/nru/nauru/gni-per-capita, его классификация - Upper middle income

Для Cook Islands GNI per capita составляет 16,217.2 долларов США согласно https://ivanstat.com/en/gni/ck.html, его классификация - High income

Для Niue GNI per capita составляет  долларов США согласно , его классификация - Upper middle income

In [179]:
life_exp.loc[life_exp['CountryDisplay'] == 'Nauru', ['WorldBankIncomeGroupDisplay', 'WorldBankIncomeGroupGroupCode']] = ['Upper_middle_income', 'WB_UMI']
life_exp.loc[life_exp['CountryDisplay'] == 'Cook Islands', ['WorldBankIncomeGroupDisplay', 'WorldBankIncomeGroupGroupCode']] = ['High_income', 'WB_HI']
# официальных данных GNI per capita за 2013 год нет.
# Ниуэ использует новозеландский доллар, получает финансовую поддержку от Новой Зеландии и имеет схожий уровень жизни с другими высокодоходными тихоокеанскими территориями.
# Поэтому страну разумно отнести к категории High income по классификации Всемирного банка.
life_exp.loc[life_exp['CountryDisplay'] == 'Niue', ['WorldBankIncomeGroupDisplay', 'WorldBankIncomeGroupGroupCode']] = ['High_income', 'WB_HI']

In [180]:
life_exp['WorldBankIncomeGroupDisplay'].isna().groupby(life_exp['RegionDisplay']).sum()

RegionDisplay
Africa                   0
Americas                 0
Eastern Mediterranean    0
Europe                   0
South_East Asia          0
Western Pacific          0
Name: WorldBankIncomeGroupDisplay, dtype: int64

Пропусков больше не осталось:) Сохраняем таблицу в нашем окружении

In [181]:
life_exp.to_csv('life_expectancy_full.csv')

### 9

Все ли признаки несут в себе полезную информацию? Почему вы так считаете? Избавьтесь от ненужных столбцов. Свой выбор аргументируйте

*Примечание. Не забудьте сохранить все изменения! В последующих заданиях вы должны работать с уже обновленными датасетами.*

In [182]:
#список признаков
life_exp.columns

Index(['index', 'GhoCode', 'GhoDisplay', 'PublishStateCode',
       'PublishStateDisplay', 'YearCode', 'YearDisplay', 'RegionCode',
       'RegionDisplay', 'WorldBankIncomeGroupGroupCode',
       'WorldBankIncomeGroupDisplay', 'CountryCode', 'CountryDisplay',
       'SexCode', 'SexDisplay', 'DisplayValue', 'Numeric'],
      dtype='object')

Колонка index не несет никакого полезного значения, всего лишь уникальный идентификатор (считаю что в фильмах он был бы полезен, но тут - нет). Не дает информации о записи

In [183]:
# удаляем index
life_exp.drop(columns=['index'], inplace=True)
life_exp

GhoCode                                       GhoDisplay  \
0     WHOSIS_000001                 Life expectancy at birth (years)   
1     WHOSIS_000002  Healthy life expectancy (HALE) at birth (years)   
2     WHOSIS_000001                 Life expectancy at birth (years)   
3     WHOSIS_000001                 Life expectancy at birth (years)   
4     WHOSIS_000015                Life expectancy at age 60 (years)   
...             ...                                              ...   
6403  WHOSIS_000001                 Life expectancy at birth (years)   
6404  WHOSIS_000015                Life expectancy at age 60 (years)   
6405  WHOSIS_000001                 Life expectancy at birth (years)   
6406  WHOSIS_000002  Healthy life expectancy (HALE) at birth (years)   
6407  WHOSIS_000001                 Life expectancy at birth (years)   

     PublishStateCode PublishStateDisplay  YearCode  YearDisplay RegionCode  \
0           PUBLISHED           Published      1990         1990        AMR   
1           PUBLISHED           Published      2012         2012        EUR   
2           PUBLISHED           Published      2000         2000        EMR   
3           PUBLISHED           Published      2000         2000        AFR   
4           PUBLISHED           Published      1990         1990       SEAR   
...               ...                 ...       ...          ...        ...   
6403        PUBLISHED           Published      2000         2000        EMR   
6404        PUBLISHED           Published      1990         1990        WPR   
6405        PUBLISHED           Published      1990         1990        AFR   
6406        PUBLISHED           Published      2012         2012        EUR   
6407        PUBLISHED           Published      2013         2013        EUR   

              RegionDisplay WorldBankIncomeGroupGroupCode  \
0                  Americas                        WB_LMI   
1                    Europe                         WB_HI   
2     Eastern Mediterranean                         WB_LI   
3                    Africa                        WB_LMI   
4           South_East Asia                        WB_LMI   
...                     ...                           ...   
6403  Eastern Mediterranean                        WB_LMI   
6404        Western Pacific                        WB_UMI   
6405                 Africa                         WB_LI   
6406                 Europe                        WB_LMI   
6407                 Europe                        WB_LMI   

     WorldBankIncomeGroupDisplay CountryCode CountryDisplay SexCode  \
0            Lower_middle_income         NIC      Nicaragua     MLE   
1                    High_income         IRL        Ireland     MLE   
2                     Low_income         YEM          Yemen    BTSX   
3            Lower_middle_income         NGA        Nigeria    FMLE   
4            Lower_middle_income         THA       Thailand    FMLE   
...                          ...         ...            ...     ...   
6403         Lower_middle_income         MAR        Morocco    BTSX   
6404         Upper_middle_income         PLW          Palau    BTSX   
6405                  Low_income         BFA   Burkina Faso    FMLE   
6406         Lower_middle_income         ALB        Albania     MLE   
6407         Lower_middle_income         ARM        Armenia    BTSX   

      SexDisplay  DisplayValue   Numeric  
0           Male            68  68.00000  
1           Male            69  69.30000  
2     Both sexes            61  61.00000  
3         Female            48  48.00000  
4         Female            19  19.00000  
...          ...           ...       ...  
6403  Both sexes            68  68.00000  
6404  Both sexes            16  16.00000  
6405      Female            51  51.00000  
6406        Male            64  63.50000  
6407  Both sexes            71  71.02699  

[6408 rows x 16 columns]

О типах отчетов: целесообразно оставить только коды, а их текстовые описания вынести в отдельный словарь. Такой подход упрощает обработку данных и группировки, исключает ошибки из-за разных вариантов написания текста и при этом сохраняет возможность при необходимости получить человеко-читаемое значение через словарь.

In [184]:
# создание справочного словаря
gho_dict = dict(life_exp[['GhoCode', 'GhoDisplay']].drop_duplicates().values)

# удаление признака GhoDisplay
life_exp.drop(columns=['GhoDisplay'], inplace=True)
life_exp

GhoCode PublishStateCode PublishStateDisplay  YearCode  \
0     WHOSIS_000001        PUBLISHED           Published      1990   
1     WHOSIS_000002        PUBLISHED           Published      2012   
2     WHOSIS_000001        PUBLISHED           Published      2000   
3     WHOSIS_000001        PUBLISHED           Published      2000   
4     WHOSIS_000015        PUBLISHED           Published      1990   
...             ...              ...                 ...       ...   
6403  WHOSIS_000001        PUBLISHED           Published      2000   
6404  WHOSIS_000015        PUBLISHED           Published      1990   
6405  WHOSIS_000001        PUBLISHED           Published      1990   
6406  WHOSIS_000002        PUBLISHED           Published      2012   
6407  WHOSIS_000001        PUBLISHED           Published      2013   

      YearDisplay RegionCode          RegionDisplay  \
0            1990        AMR               Americas   
1            2012        EUR                 Europe   
2            2000        EMR  Eastern Mediterranean   
3            2000        AFR                 Africa   
4            1990       SEAR        South_East Asia   
...           ...        ...                    ...   
6403         2000        EMR  Eastern Mediterranean   
6404         1990        WPR        Western Pacific   
6405         1990        AFR                 Africa   
6406         2012        EUR                 Europe   
6407         2013        EUR                 Europe   

     WorldBankIncomeGroupGroupCode WorldBankIncomeGroupDisplay CountryCode  \
0                           WB_LMI         Lower_middle_income         NIC   
1                            WB_HI                 High_income         IRL   
2                            WB_LI                  Low_income         YEM   
3                           WB_LMI         Lower_middle_income         NGA   
4                           WB_LMI         Lower_middle_income         THA   
...                            ...                         ...         ...   
6403                        WB_LMI         Lower_middle_income         MAR   
6404                        WB_UMI         Upper_middle_income         PLW   
6405                         WB_LI                  Low_income         BFA   
6406                        WB_LMI         Lower_middle_income         ALB   
6407                        WB_LMI         Lower_middle_income         ARM   

     CountryDisplay SexCode  SexDisplay  DisplayValue   Numeric  
0         Nicaragua     MLE        Male            68  68.00000  
1           Ireland     MLE        Male            69  69.30000  
2             Yemen    BTSX  Both sexes            61  61.00000  
3           Nigeria    FMLE      Female            48  48.00000  
4          Thailand    FMLE      Female            19  19.00000  
...             ...     ...         ...           ...       ...  
6403        Morocco    BTSX  Both sexes            68  68.00000  
6404          Palau    BTSX  Both sexes            16  16.00000  
6405   Burkina Faso    FMLE      Female            51  51.00000  
6406        Albania     MLE        Male            64  63.50000  
6407        Armenia    BTSX  Both sexes            71  71.02699  

[6408 rows x 15 columns]

In [185]:
gho_dict

{'WHOSIS_000001': 'Life expectancy at birth (years)',
 'WHOSIS_000002': 'Healthy life expectancy (HALE) at birth (years)',
 'WHOSIS_000015': 'Life expectancy at age 60 (years)'}

У колонок PublishStateCode и PublishStateDisplay нулевая полезность, так как все строки имеют значение Published

In [186]:
life_exp['PublishStateCode'].unique()

array(['PUBLISHED'], dtype=object)

In [187]:
life_exp['PublishStateDisplay'].unique()

array(['Published'], dtype=object)

В контексте нашей задачи эти признаки не влияют на анализ, поэтому удаляем

In [188]:
# удаление PublishStateCode и PublishStateDisplay
life_exp.drop(columns=['PublishStateCode', 'PublishStateDisplay'], inplace=True)
life_exp

GhoCode  YearCode  YearDisplay RegionCode          RegionDisplay  \
0     WHOSIS_000001      1990         1990        AMR               Americas   
1     WHOSIS_000002      2012         2012        EUR                 Europe   
2     WHOSIS_000001      2000         2000        EMR  Eastern Mediterranean   
3     WHOSIS_000001      2000         2000        AFR                 Africa   
4     WHOSIS_000015      1990         1990       SEAR        South_East Asia   
...             ...       ...          ...        ...                    ...   
6403  WHOSIS_000001      2000         2000        EMR  Eastern Mediterranean   
6404  WHOSIS_000015      1990         1990        WPR        Western Pacific   
6405  WHOSIS_000001      1990         1990        AFR                 Africa   
6406  WHOSIS_000002      2012         2012        EUR                 Europe   
6407  WHOSIS_000001      2013         2013        EUR                 Europe   

     WorldBankIncomeGroupGroupCode WorldBankIncomeGroupDisplay CountryCode  \
0                           WB_LMI         Lower_middle_income         NIC   
1                            WB_HI                 High_income         IRL   
2                            WB_LI                  Low_income         YEM   
3                           WB_LMI         Lower_middle_income         NGA   
4                           WB_LMI         Lower_middle_income         THA   
...                            ...                         ...         ...   
6403                        WB_LMI         Lower_middle_income         MAR   
6404                        WB_UMI         Upper_middle_income         PLW   
6405                         WB_LI                  Low_income         BFA   
6406                        WB_LMI         Lower_middle_income         ALB   
6407                        WB_LMI         Lower_middle_income         ARM   

     CountryDisplay SexCode  SexDisplay  DisplayValue   Numeric  
0         Nicaragua     MLE        Male            68  68.00000  
1           Ireland     MLE        Male            69  69.30000  
2             Yemen    BTSX  Both sexes            61  61.00000  
3           Nigeria    FMLE      Female            48  48.00000  
4          Thailand    FMLE      Female            19  19.00000  
...             ...     ...         ...           ...       ...  
6403        Morocco    BTSX  Both sexes            68  68.00000  
6404          Palau    BTSX  Both sexes            16  16.00000  
6405   Burkina Faso    FMLE      Female            51  51.00000  
6406        Albania     MLE        Male            64  63.50000  
6407        Armenia    BTSX  Both sexes            71  71.02699  

[6408 rows x 13 columns]

Имеется 2 колонки, обозначающие год. Можно удалить одну, так как они идентичны по значениям. Год критически важен для дальнейшего анализа трендов

In [189]:
life_exp['YearCode'].unique()

array([1990, 2012, 2000, 2013])

In [190]:
life_exp['YearDisplay'].unique()

array([1990, 2012, 2000, 2013])

In [191]:
# удаляем колонку YearDisplay
life_exp.drop(columns=['YearDisplay'], inplace=True)
life_exp

GhoCode  YearCode RegionCode          RegionDisplay  \
0     WHOSIS_000001      1990        AMR               Americas   
1     WHOSIS_000002      2012        EUR                 Europe   
2     WHOSIS_000001      2000        EMR  Eastern Mediterranean   
3     WHOSIS_000001      2000        AFR                 Africa   
4     WHOSIS_000015      1990       SEAR        South_East Asia   
...             ...       ...        ...                    ...   
6403  WHOSIS_000001      2000        EMR  Eastern Mediterranean   
6404  WHOSIS_000015      1990        WPR        Western Pacific   
6405  WHOSIS_000001      1990        AFR                 Africa   
6406  WHOSIS_000002      2012        EUR                 Europe   
6407  WHOSIS_000001      2013        EUR                 Europe   

     WorldBankIncomeGroupGroupCode WorldBankIncomeGroupDisplay CountryCode  \
0                           WB_LMI         Lower_middle_income         NIC   
1                            WB_HI                 High_income         IRL   
2                            WB_LI                  Low_income         YEM   
3                           WB_LMI         Lower_middle_income         NGA   
4                           WB_LMI         Lower_middle_income         THA   
...                            ...                         ...         ...   
6403                        WB_LMI         Lower_middle_income         MAR   
6404                        WB_UMI         Upper_middle_income         PLW   
6405                         WB_LI                  Low_income         BFA   
6406                        WB_LMI         Lower_middle_income         ALB   
6407                        WB_LMI         Lower_middle_income         ARM   

     CountryDisplay SexCode  SexDisplay  DisplayValue   Numeric  
0         Nicaragua     MLE        Male            68  68.00000  
1           Ireland     MLE        Male            69  69.30000  
2             Yemen    BTSX  Both sexes            61  61.00000  
3           Nigeria    FMLE      Female            48  48.00000  
4          Thailand    FMLE      Female            19  19.00000  
...             ...     ...         ...           ...       ...  
6403        Morocco    BTSX  Both sexes            68  68.00000  
6404          Palau    BTSX  Both sexes            16  16.00000  
6405   Burkina Faso    FMLE      Female            51  51.00000  
6406        Albania     MLE        Male            64  63.50000  
6407        Armenia    BTSX  Both sexes            71  71.02699  

[6408 rows x 12 columns]

Подход к идентификации регионов схож с обработкой типов статей, также создаем справочный словарь, которым можем пользоваться в будущем. Удаляем текстовую расшифровку, так как код региона читается компьютером лучше

In [192]:
# создание справочного словаря
region_dict = dict(life_exp[['RegionCode', 'RegionDisplay']].drop_duplicates().values)

# удаление признака RegionDisplay
life_exp.drop(columns=['RegionDisplay'], inplace=True)
life_exp

GhoCode  YearCode RegionCode WorldBankIncomeGroupGroupCode  \
0     WHOSIS_000001      1990        AMR                        WB_LMI   
1     WHOSIS_000002      2012        EUR                         WB_HI   
2     WHOSIS_000001      2000        EMR                         WB_LI   
3     WHOSIS_000001      2000        AFR                        WB_LMI   
4     WHOSIS_000015      1990       SEAR                        WB_LMI   
...             ...       ...        ...                           ...   
6403  WHOSIS_000001      2000        EMR                        WB_LMI   
6404  WHOSIS_000015      1990        WPR                        WB_UMI   
6405  WHOSIS_000001      1990        AFR                         WB_LI   
6406  WHOSIS_000002      2012        EUR                        WB_LMI   
6407  WHOSIS_000001      2013        EUR                        WB_LMI   

     WorldBankIncomeGroupDisplay CountryCode CountryDisplay SexCode  \
0            Lower_middle_income         NIC      Nicaragua     MLE   
1                    High_income         IRL        Ireland     MLE   
2                     Low_income         YEM          Yemen    BTSX   
3            Lower_middle_income         NGA        Nigeria    FMLE   
4            Lower_middle_income         THA       Thailand    FMLE   
...                          ...         ...            ...     ...   
6403         Lower_middle_income         MAR        Morocco    BTSX   
6404         Upper_middle_income         PLW          Palau    BTSX   
6405                  Low_income         BFA   Burkina Faso    FMLE   
6406         Lower_middle_income         ALB        Albania     MLE   
6407         Lower_middle_income         ARM        Armenia    BTSX   

      SexDisplay  DisplayValue   Numeric  
0           Male            68  68.00000  
1           Male            69  69.30000  
2     Both sexes            61  61.00000  
3         Female            48  48.00000  
4         Female            19  19.00000  
...          ...           ...       ...  
6403  Both sexes            68  68.00000  
6404  Both sexes            16  16.00000  
6405      Female            51  51.00000  
6406        Male            64  63.50000  
6407  Both sexes            71  71.02699  

[6408 rows x 11 columns]

In [193]:
region_dict

{'AMR': 'Americas',
 'EUR': 'Europe',
 'EMR': 'Eastern Mediterranean',
 'AFR': 'Africa',
 'SEAR': 'South_East Asia',
 'WPR': 'Western Pacific'}

Схожая ситуация и с классификацией доходов от Всемирного банка. Аналогично оставляем коды, для упрощения чтения компьютером. Создаем справочный словарь для придания значениям человекочитаемого вида

In [194]:
# создание справочного словаря
income_dict = dict(life_exp[['WorldBankIncomeGroupGroupCode', 'WorldBankIncomeGroupDisplay']].drop_duplicates().values)

# удаление признака WorldBankIncomeGroupDisplay
life_exp.drop(columns=['WorldBankIncomeGroupDisplay'], inplace=True)
life_exp

GhoCode  YearCode RegionCode WorldBankIncomeGroupGroupCode  \
0     WHOSIS_000001      1990        AMR                        WB_LMI   
1     WHOSIS_000002      2012        EUR                         WB_HI   
2     WHOSIS_000001      2000        EMR                         WB_LI   
3     WHOSIS_000001      2000        AFR                        WB_LMI   
4     WHOSIS_000015      1990       SEAR                        WB_LMI   
...             ...       ...        ...                           ...   
6403  WHOSIS_000001      2000        EMR                        WB_LMI   
6404  WHOSIS_000015      1990        WPR                        WB_UMI   
6405  WHOSIS_000001      1990        AFR                         WB_LI   
6406  WHOSIS_000002      2012        EUR                        WB_LMI   
6407  WHOSIS_000001      2013        EUR                        WB_LMI   

     CountryCode CountryDisplay SexCode  SexDisplay  DisplayValue   Numeric  
0            NIC      Nicaragua     MLE        Male            68  68.00000  
1            IRL        Ireland     MLE        Male            69  69.30000  
2            YEM          Yemen    BTSX  Both sexes            61  61.00000  
3            NGA        Nigeria    FMLE      Female            48  48.00000  
4            THA       Thailand    FMLE      Female            19  19.00000  
...          ...            ...     ...         ...           ...       ...  
6403         MAR        Morocco    BTSX  Both sexes            68  68.00000  
6404         PLW          Palau    BTSX  Both sexes            16  16.00000  
6405         BFA   Burkina Faso    FMLE      Female            51  51.00000  
6406         ALB        Albania     MLE        Male            64  63.50000  
6407         ARM        Armenia    BTSX  Both sexes            71  71.02699  

[6408 rows x 10 columns]

In [195]:
income_dict

{'WB_LMI': 'Lower_middle_income',
 'WB_HI': 'High_income',
 'WB_LI': 'Low_income',
 'WB_UMI': 'Upper_middle_income'}

Ситуация не меняется и со страной и полом, создаем соответсвующие словари

In [196]:
# создание справочного словаря
country_dict = dict(life_exp[['CountryCode', 'CountryDisplay']].drop_duplicates().values)

# удаление признака WorldBankIncomeGroupDisplay
life_exp.drop(columns=['CountryDisplay'], inplace=True)
life_exp

GhoCode  YearCode RegionCode WorldBankIncomeGroupGroupCode  \
0     WHOSIS_000001      1990        AMR                        WB_LMI   
1     WHOSIS_000002      2012        EUR                         WB_HI   
2     WHOSIS_000001      2000        EMR                         WB_LI   
3     WHOSIS_000001      2000        AFR                        WB_LMI   
4     WHOSIS_000015      1990       SEAR                        WB_LMI   
...             ...       ...        ...                           ...   
6403  WHOSIS_000001      2000        EMR                        WB_LMI   
6404  WHOSIS_000015      1990        WPR                        WB_UMI   
6405  WHOSIS_000001      1990        AFR                         WB_LI   
6406  WHOSIS_000002      2012        EUR                        WB_LMI   
6407  WHOSIS_000001      2013        EUR                        WB_LMI   

     CountryCode SexCode  SexDisplay  DisplayValue   Numeric  
0            NIC     MLE        Male            68  68.00000  
1            IRL     MLE        Male            69  69.30000  
2            YEM    BTSX  Both sexes            61  61.00000  
3            NGA    FMLE      Female            48  48.00000  
4            THA    FMLE      Female            19  19.00000  
...          ...     ...         ...           ...       ...  
6403         MAR    BTSX  Both sexes            68  68.00000  
6404         PLW    BTSX  Both sexes            16  16.00000  
6405         BFA    FMLE      Female            51  51.00000  
6406         ALB     MLE        Male            64  63.50000  
6407         ARM    BTSX  Both sexes            71  71.02699  

[6408 rows x 9 columns]

In [197]:
country_dict

{'NIC': 'Nicaragua',
 'IRL': 'Ireland',
 'YEM': 'Yemen',
 'NGA': 'Nigeria',
 'THA': 'Thailand',
 'CHL': 'Chile',
 'ZWE': 'Zimbabwe',
 'DEU': 'Germany',
 'ESP': 'Spain',
 'BWA': 'Botswana',
 'PAK': 'Pakistan',
 'NIU': 'Niue',
 'WSM': 'Samoa',
 'JPN': 'Japan',
 'MNG': 'Mongolia',
 'BLZ': 'Belize',
 'MEX': 'Mexico',
 'BRA': 'Brazil',
 'AUS': 'Australia',
 'RWA': 'Rwanda',
 'BOL': 'Bolivia (Plurinational State of)',
 'AND': 'Andorra',
 'LCA': 'Saint Lucia',
 'DJI': 'Djibouti',
 'BTN': 'Bhutan',
 'TON': 'Tonga',
 'BGR': 'Bulgaria',
 'SYR': 'Syrian Arab Republic',
 'MMR': 'Myanmar',
 'BRB': 'Barbados',
 'KWT': 'Kuwait',
 'GRD': 'Grenada',
 'SUR': 'Suriname',
 'POL': 'Poland',
 'NER': 'Niger',
 'ARM': 'Armenia',
 'STP': 'Sao Tome and Principe',
 'GIN': 'Guinea',
 'PAN': 'Panama',
 'KOR': 'Republic of Korea',
 'CZE': 'Czech Republic',
 'SLB': 'Solomon Islands',
 'ISL': 'Iceland',
 'KEN': 'Kenya',
 'IND': 'India',
 'GTM': 'Guatemala',
 'BLR': 'Belarus',
 'VUT': 'Vanuatu',
 'MYS': 'Malaysia',
 '

In [198]:
# создание справочного словаря
sex_dict = dict(life_exp[['SexCode', 'SexDisplay']].drop_duplicates().values)

# удаление признака WorldBankIncomeGroupDisplay
life_exp.drop(columns=['SexDisplay'], inplace=True)
life_exp

GhoCode  YearCode RegionCode WorldBankIncomeGroupGroupCode  \
0     WHOSIS_000001      1990        AMR                        WB_LMI   
1     WHOSIS_000002      2012        EUR                         WB_HI   
2     WHOSIS_000001      2000        EMR                         WB_LI   
3     WHOSIS_000001      2000        AFR                        WB_LMI   
4     WHOSIS_000015      1990       SEAR                        WB_LMI   
...             ...       ...        ...                           ...   
6403  WHOSIS_000001      2000        EMR                        WB_LMI   
6404  WHOSIS_000015      1990        WPR                        WB_UMI   
6405  WHOSIS_000001      1990        AFR                         WB_LI   
6406  WHOSIS_000002      2012        EUR                        WB_LMI   
6407  WHOSIS_000001      2013        EUR                        WB_LMI   

     CountryCode SexCode  DisplayValue   Numeric  
0            NIC     MLE            68  68.00000  
1            IRL     MLE            69  69.30000  
2            YEM    BTSX            61  61.00000  
3            NGA    FMLE            48  48.00000  
4            THA    FMLE            19  19.00000  
...          ...     ...           ...       ...  
6403         MAR    BTSX            68  68.00000  
6404         PLW    BTSX            16  16.00000  
6405         BFA    FMLE            51  51.00000  
6406         ALB     MLE            64  63.50000  
6407         ARM    BTSX            71  71.02699  

[6408 rows x 8 columns]

In [199]:
sex_dict

{'MLE': 'Male', 'BTSX': 'Both sexes', 'FMLE': 'Female'}

Колонки DisplayValue и Numeric не удаляем, так как они впервую очередь важны для анализа. Это основная числовая информация, на которой строятся все расчёты, группировки, корреляции и визуализации. Удаление этих столбцов лишит нас данных для анализа.

In [200]:
# сохраняем датасет
life_exp.to_csv('life_expectancy_after_task_9.csv')

### 10

Посчитайте, насколько сильно коррелируют друг с другом потребления разных видов алкоголя (`beer_servings`,	`spirit_servings` и	`wine_servings`). Создайте датафрейм с попарными корреляциями этих столбцов друг с другом. Какие выводы можно сделать?

In [201]:
alcohol_cols = ['beer_servings', 'spirit_servings', 'wine_servings']
drinks[alcohol_cols].corr()

beer_servings  spirit_servings  wine_servings
beer_servings         1.000000         0.458819       0.527172
spirit_servings       0.458819         1.000000       0.194797
wine_servings         0.527172         0.194797       1.000000

Корреляции рассчитаны по среднему потреблению алкоголя на человека в разных странах

beer_servings и wine_servings имеют умеренную положительную связь (≈0.53)

beer_servings и spirit_servings тоже положительно связаны, но слабее (≈0.46)

spirit_servings и wine_servings почти не коррелируют (≈0.19)

вывод: страны, где люди пьют больше пива, чаще пьют и вино, а спиртное не так сильно связано с другими видами

dcs:
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.corr.html

### 11

С помощью датасета из интернета (файл iso.csv) мы мержа их добавляем к каждой строчке 3-х значный код классификации ISO, в дальнейшем эта стандартизация поможет нам объединить датасеты

In [202]:
iso = pd.read_csv('iso.csv')

In [203]:
# мержим таблицы
drinks = drinks.merge(
    iso,
    left_on='country',
    right_on='country',
    how='left'
)

drinks = drinks.drop(columns=['Unnamed: 0'])

In [204]:
drinks

index      country  beer_servings  spirit_servings  wine_servings  \
0        0  Afghanistan              0                0              0   
1        1      Albania             89              132             54   
2        2      Algeria             25                0             14   
3        3      Andorra            245              138            312   
4        4       Angola            217               57             45   
..     ...          ...            ...              ...            ...   
188    188    Venezuela            333              100              3   
189    189      Vietnam            111                2              1   
190    190        Yemen              6                0              0   
191    191       Zambia             32               19              4   
192    192     Zimbabwe             64               18              4   

     total_litres_of_pure_alcohol CountryCode  
0                             0.0         AFG  
1                             4.9         ALB  
2                             0.7         DZA  
3                            12.4         AND  
4                             5.9         AGO  
..                            ...         ...  
188                           7.7         VEN  
189                           2.0         VNM  
190                           0.1         YEM  
191                           2.5         ZMB  
192                           4.7         ZWE  

[193 rows x 7 columns]

In [205]:
# количество пропусков
drinks.isna().sum()

index                           0
country                         0
beer_servings                   0
spirit_servings                 0
wine_servings                   0
total_litres_of_pure_alcohol    0
CountryCode                     0
dtype: int64

In [206]:
# объединяем по коду страны, оставляем все строки из life_exp
merged_df = life_exp.merge(
    drinks.drop(columns=['index', 'country']),
    on='CountryCode',
    how='left',
    suffixes=('', '_drinks')
)

In [207]:
# количество пропусков
merged_df.isna().sum()

GhoCode                           0
YearCode                          0
RegionCode                        0
WorldBankIncomeGroupGroupCode     0
CountryCode                       0
SexCode                           0
DisplayValue                      0
Numeric                           0
beer_servings                    39
spirit_servings                  39
wine_servings                    39
total_litres_of_pure_alcohol     39
dtype: int64

Главной таблицей является life_exp с данными о продолжительности жизни, сопутствующей — drinks с информацией о потреблении алкоголя. Таблица о жизни более детализированная (по годам, полу, показателям), а таблица об алкоголе агрегирована на уровне страны. Мы хотим изучить зависимость продолжительности жизни от внешних факторов, в частности уровня употребления алкоголя, доходов стран, региона и пола. Поэтому используем левое соединение (left join) по CountryCode: сохраняем все строки из главной таблицы, а данные из сопутствующей подтягиваем туда, где они есть. По объединению таблиц не получилось задействовать все строки по алкоголю — в 39 случаях (beer_servings, spirit_servings, wine_servings, total_litres_of_pure_alcohol) не подтянулись значения. Для этих стран нет данных в таблице drinks, либо коды стран не совпали.

Эти строки остаются в главной таблице life_exp с NaN в столбцах алкоголя. Это нормальный результат для левостороннего соединения — мы не теряем данные по продолжительности жизни, а в дальнейшем при анализе можно либо игнорировать пропуски, либо заполнять их дополнительной информацией, если она есть (например, через GNI или усреднённые показатели).

In [208]:
# сохранить датасет
merged_df.to_csv('life_expectancy_after_task_11.csv')

### 12

Осуществите группировку данных по странам и типу научной статьи (многомерная группировка). В качестве столбцов значений для группировки возьмите оцененную продолжительность жизни и общее потребление алкоголя в литрах. В качестве агреггирующих функций для продолжительности жизни возьмите среднее, медиану, минимум и максимум, а для потребления алкоголя — агреггирующую функцию/функции выберите самостоятельно. Как вы можете прокомментировать свой выбор и что вы наблюдаете?

In [209]:
# группируем по странам и типу научной статьи и вычисляем аггрегирующие функции

grouped = merged_df.groupby(['CountryCode', 'GhoCode']).agg(
    life_mean=('Numeric', 'mean'),
    life_median=('Numeric', 'median'),
    life_min=('Numeric', 'min'),
    life_max=('Numeric', 'max'),
    alcohol_mean=('total_litres_of_pure_alcohol', 'mean')
).reset_index()
grouped

CountryCode        GhoCode  life_mean  life_median  life_min  life_max  \
0           AFG  WHOSIS_000001  56.311805    57.000000      49.0  61.97733   
1           AFG  WHOSIS_000002  47.833333    48.800000      44.6  50.50000   
2           AFG  WHOSIS_000015  15.223012    15.061535      13.0  17.00000   
3           AGO  WHOSIS_000001  47.852151    48.500000      41.0  53.19343   
4           AGO  WHOSIS_000002  42.444444    43.300000      37.9  45.60000   
..          ...            ...        ...          ...       ...       ...   
577         ZMB  WHOSIS_000002  44.900000    48.700000      34.6  51.40000   
578         ZMB  WHOSIS_000015  16.068835    16.000000      14.0  18.10310   
579         ZWE  WHOSIS_000001  55.186778    58.363385      42.0  64.00000   
580         ZWE  WHOSIS_000002  45.222222    47.700000      36.4  51.80000   
581         ZWE  WHOSIS_000015  17.369381    17.654040      15.0  19.00000   

     alcohol_mean  
0             0.0  
1             0.0  
2             0.0  
3             5.9  
4             5.9  
..            ...  
577           2.5  
578           2.5  
579           4.7  
580           4.7  
581           4.7  

[582 rows x 7 columns]

Для продолжительности жизни (Numeric) беру mean, median, min и max, чтобы видеть среднюю продолжительность, центральное значение и разброс.

Для потребления алкоголя (total_litres_of_pure_alcohol) беру mean, так как интересно среднее потребление на человека в каждой стране и для каждого типа статьи.

### 13

Вставьте любые два столбца из предыдущего задания, которые вы получили путем группировки, в исходную таблицу в качестве двух новых столбцов (назвать вы их можете как хотите). Разумеется, значения этих столбцов должны соответствовать значениям исходной таблицы по указанным в прошлом задании категориям.

*Примечание. Не забудьте сохранить все изменения! В последующих заданиях вы должны работать с обновленным датасетом.*

In [210]:
# решили вставить life_mean и alcohol_mean
columns_to_merge = grouped[['CountryCode', 'GhoCode', 'life_mean', 'alcohol_mean']]
life_exp = life_exp.merge(
    columns_to_merge,
    on=['CountryCode', 'GhoCode'],
    how='left'
)
life_exp = life_exp.rename(columns={
    'life_mean': 'avg_life_by_country',
    'alcohol_mean': 'avg_alcohol_by_country'
})
life_exp

GhoCode  YearCode RegionCode WorldBankIncomeGroupGroupCode  \
0     WHOSIS_000001      1990        AMR                        WB_LMI   
1     WHOSIS_000002      2012        EUR                         WB_HI   
2     WHOSIS_000001      2000        EMR                         WB_LI   
3     WHOSIS_000001      2000        AFR                        WB_LMI   
4     WHOSIS_000015      1990       SEAR                        WB_LMI   
...             ...       ...        ...                           ...   
6403  WHOSIS_000001      2000        EMR                        WB_LMI   
6404  WHOSIS_000015      1990        WPR                        WB_UMI   
6405  WHOSIS_000001      1990        AFR                         WB_LI   
6406  WHOSIS_000002      2012        EUR                        WB_LMI   
6407  WHOSIS_000001      2013        EUR                        WB_LMI   

     CountryCode SexCode  DisplayValue   Numeric  avg_life_by_country  \
0            NIC     MLE            68  68.00000            72.667402   
1            IRL     MLE            69  69.30000            69.911111   
2            YEM    BTSX            61  61.00000            61.567050   
3            NGA    FMLE            48  48.00000            50.473338   
4            THA    FMLE            19  19.00000            19.895824   
...          ...     ...           ...       ...                  ...   
6403         MAR    BTSX            68  68.00000            68.574297   
6404         PLW    BTSX            16  16.00000            17.313487   
6405         BFA    FMLE            51  51.00000            53.880190   
6406         ALB     MLE            64  63.50000            63.800000   
6407         ARM    BTSX            71  71.02699            70.046697   

      avg_alcohol_by_country  
0                        3.5  
1                       11.4  
2                        0.1  
3                        9.1  
4                        6.4  
...                      ...  
6403                     0.5  
6404                     6.9  
6405                     4.3  
6406                     4.9  
6407                     3.8  

[6408 rows x 10 columns]

dcs:
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html

### 14

Используя группировки, аргументированно ответьте на вопрос: на каких континентах средняя ожидаемая продолжительность жизни выше у мужчин, а на каких у женщин?

А медианная ожидаемая продолжительность?

А минимальная ожидаемая продолжительность?

Сделайте выводы!

*Подсказка. Казалось бы, при чем здесь тип научной статьи?*

In [211]:
# группируем для наглядности
grouped = life_exp.pivot_table(
    index=['RegionCode', 'SexCode'],
    columns='GhoCode',
    values='Numeric',
    aggfunc=['mean', 'median', 'min']
)
grouped

mean                                    median  \
GhoCode            WHOSIS_000001 WHOSIS_000002 WHOSIS_000015 WHOSIS_000001   
RegionCode SexCode                                                           
AFR        BTSX        56.245705     49.136232     16.110551     57.000000   
           FMLE        57.845527     50.094203     16.792841     58.000000   
           MLE         54.724349     48.190580     15.331986     55.000000   
AMR        BTSX        73.028041     63.838095     20.690960     74.000000   
           FMLE        75.873706     65.971429     22.131179     77.000000   
           MLE         70.282002     61.752381     19.175239     71.000000   
EMR        BTSX        68.133069     59.192647     17.935767     70.365680   
           FMLE        69.880894     59.848529     18.845779     73.000000   
           MLE         66.595512     58.510294     17.199309     69.000000   
EUR        BTSX        75.233666     66.658491     20.566757     76.000000   
           FMLE        78.454599     69.118868     22.292036     79.000000   
           MLE         71.976935     64.174214     18.476702     72.518745   
SEAR       BTSX        66.345093     59.403030     17.360583     67.500000   
           FMLE        68.188877     60.909091     18.342758     68.968250   
           MLE         64.491738     57.942424     16.291729     65.000000   
WPR        BTSX        70.985250     62.924691     18.785198     71.000000   
           FMLE        73.538356     64.733333     20.359732     73.500000   
           MLE         68.585153     61.219753     17.236480     68.124050   

                                                         min                \
GhoCode            WHOSIS_000002 WHOSIS_000015 WHOSIS_000001 WHOSIS_000002   
RegionCode SexCode                                                           
AFR        BTSX            49.35      16.00000          38.0          33.1   
           FMLE            50.00      16.94181          38.0          33.4   
           MLE             48.80      15.14800          38.0          32.8   
AMR        BTSX            63.80      21.00000          54.0          47.8   
           FMLE            66.20      22.53821          56.0          48.5   
           MLE             62.10      19.34305          52.0          47.1   
EMR        BTSX            61.65      18.00000          42.0          41.6   
           FMLE            63.10      18.89404          44.0          42.0   
           MLE             60.80      17.00000          41.0          41.0   
EUR        BTSX            67.40      20.11892          62.0          54.3   
           FMLE            70.00      22.00000          65.0          56.6   
           MLE             64.80      18.00000          58.0          51.2   
SEAR       BTSX            58.90      17.00000          50.0          50.0   
           FMLE            59.90      18.00000          51.0          51.2   
           MLE             58.20      16.00000          48.0          48.8   
WPR        BTSX            62.20      18.00000          53.0          50.2   
           FMLE            63.70      19.00000          54.0          51.8   
           MLE             60.80      16.65897          51.0          48.6   

                                  
GhoCode            WHOSIS_000015  
RegionCode SexCode                
AFR        BTSX         11.00000  
           FMLE         11.00000  
           MLE          11.00000  
AMR        BTSX         15.00000  
           FMLE         16.00000  
           MLE          12.86658  
EMR        BTSX         14.00000  
           FMLE         14.00000  
           MLE          13.00000  
EUR        BTSX         15.00000  
           FMLE         16.00000  
           MLE          12.00000  
SEAR       BTSX         13.00000  
           FMLE         12.00000  
           MLE          12.00000  
WPR        BTSX         13.00000  
           FMLE         15.00000  
           MLE          12.00000

Если посмотреть на данные по продолжительности жизни, становится заметно, что женщины в среднем живут дольше мужчин на всех континентах. Например, в Африке средняя продолжительность жизни женщин около 57,8 лет, а мужчин — 54,7 лет, разница примерно 3 года. В Америке женщины живут в среднем 75,9 лет, мужчины — 70,3, а в Европе — 78,5 против 72 лет. Причём эта тенденция сохраняется, независимо от того, какой тип статьи учитывается — будь то показатели с рождения, после 60 лет или ожидаемая здоровая жизнь.

Если смотреть на медиану, картина почти такая же: у женщин она выше, чем у мужчин, на всех континентах. Например, в Америке медиана для женщин 77 лет, для мужчин 71, в Европе — 79 против 72,5 года.

Минимальные значения тоже чаще выше у женщин или примерно равны мужчинам. Разница здесь меньше, потому что минимумы зависят от отдельных экстремальных случаев, а не от общей тенденции. Например, в Африке минимальная продолжительность без болезней для женщин 33,4 года, для мужчин 32,8; в Америке — 48,5 против 47,1 года.

В целом можно сделать вывод, что на всех континентах женщины живут дольше мужчин. Разрыв особенно заметен в среднем и медианном значении, а минимальные показатели менее показательны. Анализ разных типов статей подтверждает эту закономерность — данные согласованы между собой.

### 15

Работая лишь с общим объединенным датасетом и не используя исходную таблицу `drinks`, подсчитайте среднее потребление каждого вида алкоголя и среднее общее количество литров потребляемого алкоголя на человека по всем континентам. Занесите ваши результаты в отдельный датафрейм!

*Подсказка. Задача немного сложнее, чем может показаться на первый взгляд — в объединенном датасете страны встречаются разное количество раз, и из-за этого могут возникнуть определенные проблемы. Если так случится, надо подумать, как это обойти!*

*Примечание. Разумеется, это необходимо сделать автоматизированно, а не перебирая каждый континент по отдельности.*

In [212]:
# сначала находим средние значения по странам
country_avg = merged_df.groupby(['RegionCode', 'CountryCode'])[
    ['beer_servings', 'spirit_servings', 'wine_servings', 'total_litres_of_pure_alcohol']
].mean()
# потом средние значения по регионам
continent_avg = country_avg.groupby('RegionCode')[
    ['beer_servings', 'spirit_servings', 'wine_servings', 'total_litres_of_pure_alcohol']
].mean()
continent_avg

beer_servings  spirit_servings  wine_servings  \
RegionCode                                                  
AFR             68.826087        17.304348      18.000000   
AMR            155.600000       148.257143      37.514286   
EMR             10.428571        21.190476       4.857143   
EUR            175.132075       130.415094     123.528302   
SEAR            14.818182        44.090909       0.454545   
WPR             81.962963        66.851852      27.740741   

            total_litres_of_pure_alcohol  
RegionCode                                
AFR                             3.360870  
AMR                             6.102857  
EMR                             0.714286  
EUR                             7.873585  
SEAR                            1.063636  
WPR                             3.637037

Датафрейм успешно создан

### 16

Создание новых признаков (feature engineering) является одним из основных средств улучшения качества работы алгоритмов машинного обучения на этапе обработки данных, а также отличный способ увеличить глубину ваших выводов из проделанного анализа в целом! Частично мы с вами уже осуществляли feature engineering, когда добавляли новые столбцы в задании 13.

Теперь давайте добавим в таблицу столбец, который будет показывать, какое общее количество servings per person производится в среднем по стране, к которой относится научная статья. Столбец для этого признака назовите `total_servings`.

Чем может быть полезен такой признак?

***Бонус (2 бон. балла):*** Придумайте еще какой-нибудь свой осмысленный признак, который может быть полезен для анализа (несет в себе какую-то информацию), и добавьте его в таблицу. Обязательно аргументируйте, чем полезен ваш признак.

In [213]:
# создаем total_servings
merged_df['total_servings'] = merged_df.groupby('CountryCode')[
    ['beer_servings', 'spirit_servings', 'wine_servings']
].transform('mean').sum(axis=1)

merged_df

GhoCode  YearCode RegionCode WorldBankIncomeGroupGroupCode  \
0     WHOSIS_000001      1990        AMR                        WB_LMI   
1     WHOSIS_000002      2012        EUR                         WB_HI   
2     WHOSIS_000001      2000        EMR                         WB_LI   
3     WHOSIS_000001      2000        AFR                        WB_LMI   
4     WHOSIS_000015      1990       SEAR                        WB_LMI   
...             ...       ...        ...                           ...   
6403  WHOSIS_000001      2000        EMR                        WB_LMI   
6404  WHOSIS_000015      1990        WPR                        WB_UMI   
6405  WHOSIS_000001      1990        AFR                         WB_LI   
6406  WHOSIS_000002      2012        EUR                        WB_LMI   
6407  WHOSIS_000001      2013        EUR                        WB_LMI   

     CountryCode SexCode  DisplayValue   Numeric  beer_servings  \
0            NIC     MLE            68  68.00000           78.0   
1            IRL     MLE            69  69.30000          313.0   
2            YEM    BTSX            61  61.00000            6.0   
3            NGA    FMLE            48  48.00000           42.0   
4            THA    FMLE            19  19.00000           99.0   
...          ...     ...           ...       ...            ...   
6403         MAR    BTSX            68  68.00000           12.0   
6404         PLW    BTSX            16  16.00000          306.0   
6405         BFA    FMLE            51  51.00000           25.0   
6406         ALB     MLE            64  63.50000           89.0   
6407         ARM    BTSX            71  71.02699           21.0   

      spirit_servings  wine_servings  total_litres_of_pure_alcohol  \
0               118.0            1.0                           3.5   
1               118.0          165.0                          11.4   
2                 0.0            0.0                           0.1   
3                 5.0            2.0                           9.1   
4               258.0            1.0                           6.4   
...               ...            ...                           ...   
6403              6.0           10.0                           0.5   
6404             63.0           23.0                           6.9   
6405              7.0            7.0                           4.3   
6406            132.0           54.0                           4.9   
6407            179.0           11.0                           3.8   

      total_servings  
0              197.0  
1              596.0  
2                6.0  
3               49.0  
4              358.0  
...              ...  
6403            28.0  
6404           392.0  
6405            39.0  
6406           275.0  
6407           211.0  

[6408 rows x 13 columns]

docs:

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.transform.html

Такой признак полезен в:

Сравнении стран – можно сразу увидеть, где в среднем пьют больше, без разбиения по видам алкоголя

Визуализация и анализ – удобно строить графики среднее потребление от средней продолжительности жизни и наоборот

Можно анализировать связь между общим алкоголем и другими социально-экономическими показателями

Добавим от себя интересный признак - долю типов алкоголя, которые потребляются в стране

In [214]:
merged_df['alcohol_diversity'] = merged_df[['beer_servings', 'spirit_servings', 'wine_servings']].gt(0).sum(axis=1) / 3
merged_df

GhoCode  YearCode RegionCode WorldBankIncomeGroupGroupCode  \
0     WHOSIS_000001      1990        AMR                        WB_LMI   
1     WHOSIS_000002      2012        EUR                         WB_HI   
2     WHOSIS_000001      2000        EMR                         WB_LI   
3     WHOSIS_000001      2000        AFR                        WB_LMI   
4     WHOSIS_000015      1990       SEAR                        WB_LMI   
...             ...       ...        ...                           ...   
6403  WHOSIS_000001      2000        EMR                        WB_LMI   
6404  WHOSIS_000015      1990        WPR                        WB_UMI   
6405  WHOSIS_000001      1990        AFR                         WB_LI   
6406  WHOSIS_000002      2012        EUR                        WB_LMI   
6407  WHOSIS_000001      2013        EUR                        WB_LMI   

     CountryCode SexCode  DisplayValue   Numeric  beer_servings  \
0            NIC     MLE            68  68.00000           78.0   
1            IRL     MLE            69  69.30000          313.0   
2            YEM    BTSX            61  61.00000            6.0   
3            NGA    FMLE            48  48.00000           42.0   
4            THA    FMLE            19  19.00000           99.0   
...          ...     ...           ...       ...            ...   
6403         MAR    BTSX            68  68.00000           12.0   
6404         PLW    BTSX            16  16.00000          306.0   
6405         BFA    FMLE            51  51.00000           25.0   
6406         ALB     MLE            64  63.50000           89.0   
6407         ARM    BTSX            71  71.02699           21.0   

      spirit_servings  wine_servings  total_litres_of_pure_alcohol  \
0               118.0            1.0                           3.5   
1               118.0          165.0                          11.4   
2                 0.0            0.0                           0.1   
3                 5.0            2.0                           9.1   
4               258.0            1.0                           6.4   
...               ...            ...                           ...   
6403              6.0           10.0                           0.5   
6404             63.0           23.0                           6.9   
6405              7.0            7.0                           4.3   
6406            132.0           54.0                           4.9   
6407            179.0           11.0                           3.8   

      total_servings  alcohol_diversity  
0              197.0           1.000000  
1              596.0           1.000000  
2                6.0           0.333333  
3               49.0           1.000000  
4              358.0           1.000000  
...              ...                ...  
6403            28.0           1.000000  
6404           392.0           1.000000  
6405            39.0           1.000000  
6406           275.0           1.000000  
6407           211.0           1.000000  

[6408 rows x 14 columns]

docs:
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.gt.html

Это полезно, потому что:

Показывает разнообразие алкогольной культуры в стране

Может быть связано с образом жизни и социальными привычками, а значит — косвенно с ожидаемой продолжительностью жизни

Отличается от total_servings или total_litres_of_pure_alcohol, которые учитывают количество, а не разнообразие, что создает ещё одну сторону для взгляда и анализа

### 17

Есть ли в данных категориальные признаки, которые принимают значения строк, а не чисел? Если да, то для многих алгоритмов это может стать серьезным препятствием, поэтому закодируйте категориальные признаки так, чтобы к данным можно было применить любые алгоритмы. Аргументируйте выбор методов кодирования.

*Подсказка. Вам могут помочь Label encoding и One-Hot Encoding. Но будьте внимательны! У каждого из этих методов есть свои сильные и слабые стороны, а также ограничения применимости.*

Безусловно есть категориальные признаки, которые принимают значения строк, а не чисел

In [215]:
# кодируем GhoCode, Sex, Region, IncomeGroup
categorical_cols = ['GhoCode', 'RegionCode', 'WorldBankIncomeGroupGroupCode', 'SexCode']
encoded_df = pd.get_dummies(merged_df, columns=categorical_cols, prefix=categorical_cols)
encoded_df

YearCode CountryCode  DisplayValue   Numeric  beer_servings  \
0         1990         NIC            68  68.00000           78.0   
1         2012         IRL            69  69.30000          313.0   
2         2000         YEM            61  61.00000            6.0   
3         2000         NGA            48  48.00000           42.0   
4         1990         THA            19  19.00000           99.0   
...        ...         ...           ...       ...            ...   
6403      2000         MAR            68  68.00000           12.0   
6404      1990         PLW            16  16.00000          306.0   
6405      1990         BFA            51  51.00000           25.0   
6406      2012         ALB            64  63.50000           89.0   
6407      2013         ARM            71  71.02699           21.0   

      spirit_servings  wine_servings  total_litres_of_pure_alcohol  \
0               118.0            1.0                           3.5   
1               118.0          165.0                          11.4   
2                 0.0            0.0                           0.1   
3                 5.0            2.0                           9.1   
4               258.0            1.0                           6.4   
...               ...            ...                           ...   
6403              6.0           10.0                           0.5   
6404             63.0           23.0                           6.9   
6405              7.0            7.0                           4.3   
6406            132.0           54.0                           4.9   
6407            179.0           11.0                           3.8   

      total_servings  alcohol_diversity  ...  RegionCode_EUR  RegionCode_SEAR  \
0              197.0           1.000000  ...           False            False   
1              596.0           1.000000  ...            True            False   
2                6.0           0.333333  ...           False            False   
3               49.0           1.000000  ...           False            False   
4              358.0           1.000000  ...           False             True   
...              ...                ...  ...             ...              ...   
6403            28.0           1.000000  ...           False            False   
6404           392.0           1.000000  ...           False            False   
6405            39.0           1.000000  ...           False            False   
6406           275.0           1.000000  ...            True            False   
6407           211.0           1.000000  ...            True            False   

      RegionCode_WPR  WorldBankIncomeGroupGroupCode_WB_HI  \
0              False                                False   
1              False                                 True   
2              False                                False   
3              False                                False   
4              False                                False   
...              ...                                  ...   
6403           False                                False   
6404            True                                False   
6405           False                                False   
6406           False                                False   
6407           False                                False   

      WorldBankIncomeGroupGroupCode_WB_LI  \
0                                   False   
1                                   False   
2                                    True   
3                                   False   
4                                   False   
...                                   ...   
6403                                False   
6404                                False   
6405                                 True   
6406                                False   
6407                                False   

      WorldBankIncomeGroupGroupCode_WB_LMI  \
0                                     True 

docs:
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.get_dummies.html

Аргументация:

У нас есть несколько категориальных признаков: GhoCode, RegionCode, WorldBankIncomeGroupGroupCode и SexCode. Они хранят текстовые метки, а большинство алгоритмов машинного обучения работать с текстом напрямую не умеют. Поэтому мы их кодируем. Я использовал One-Hot Encoding, потому что у этих признаков нет естественного порядка — нельзя сказать, что одна категория «больше» или «меньше» другой. One-Hot превращает каждую категорию в отдельный бинарный столбец, и алгоритмы могут корректно работать с этими признаками, не вводя лишнюю логику. Так проще и безопаснее для анализа и построения моделей.

In [216]:
# кодируем страны
unique_countries = merged_df['CountryCode'].unique()
country_label_dict = {country: i for i, country in enumerate(unique_countries)}
merged_df['CountryCode_encoded'] = merged_df['CountryCode'].map(country_label_dict)
merged_df

GhoCode  YearCode RegionCode WorldBankIncomeGroupGroupCode  \
0     WHOSIS_000001      1990        AMR                        WB_LMI   
1     WHOSIS_000002      2012        EUR                         WB_HI   
2     WHOSIS_000001      2000        EMR                         WB_LI   
3     WHOSIS_000001      2000        AFR                        WB_LMI   
4     WHOSIS_000015      1990       SEAR                        WB_LMI   
...             ...       ...        ...                           ...   
6403  WHOSIS_000001      2000        EMR                        WB_LMI   
6404  WHOSIS_000015      1990        WPR                        WB_UMI   
6405  WHOSIS_000001      1990        AFR                         WB_LI   
6406  WHOSIS_000002      2012        EUR                        WB_LMI   
6407  WHOSIS_000001      2013        EUR                        WB_LMI   

     CountryCode SexCode  DisplayValue   Numeric  beer_servings  \
0            NIC     MLE            68  68.00000           78.0   
1            IRL     MLE            69  69.30000          313.0   
2            YEM    BTSX            61  61.00000            6.0   
3            NGA    FMLE            48  48.00000           42.0   
4            THA    FMLE            19  19.00000           99.0   
...          ...     ...           ...       ...            ...   
6403         MAR    BTSX            68  68.00000           12.0   
6404         PLW    BTSX            16  16.00000          306.0   
6405         BFA    FMLE            51  51.00000           25.0   
6406         ALB     MLE            64  63.50000           89.0   
6407         ARM    BTSX            71  71.02699           21.0   

      spirit_servings  wine_servings  total_litres_of_pure_alcohol  \
0               118.0            1.0                           3.5   
1               118.0          165.0                          11.4   
2                 0.0            0.0                           0.1   
3                 5.0            2.0                           9.1   
4               258.0            1.0                           6.4   
...               ...            ...                           ...   
6403              6.0           10.0                           0.5   
6404             63.0           23.0                           6.9   
6405              7.0            7.0                           4.3   
6406            132.0           54.0                           4.9   
6407            179.0           11.0                           3.8   

      total_servings  alcohol_diversity  CountryCode_encoded  
0              197.0           1.000000                    0  
1              596.0           1.000000                    1  
2                6.0           0.333333                    2  
3               49.0           1.000000                    3  
4              358.0           1.000000                    4  
...              ...                ...                  ...  
6403            28.0           1.000000                  190  
6404           392.0           1.000000                   90  
6405            39.0           1.000000                  153  
6406           275.0           1.000000                  191  
6407           211.0           1.000000                   35  

[6408 rows x 15 columns]

Аргументация:

Для признака CountryCode мы применяем Label Encoding, потому что каждая страна уникальна и их слишком много для применения One-Hot Encoding. Если бы мы сделали One-Hot, получится огромное количество новых столбцов, что сильно раздует датасет и усложнит работу алгоритмов. При Label Encoding каждая страна получает уникальный числовой идентификатор, который модели могут использовать как категориальную метку без создания лишних колонок.

Важно понимать, что числа не несут порядковой информации — это именно идентификаторы. Сравнения «меньше-больше» по ним не имеют смысла, но алгоритмы могут использовать их для разделения данных на группы. Такой подход особенно удобен, когда количество категорий велико, как в нашем случае со странами.

### 18

Посчитать, для каждой страны, в какие годы наблюдается наибольший разрыв между ожидаемой продолжительностью жизни женщин и мужчин. Вывести топ-5 стран с наибольшей средней разницей за весь период наблюдений. Также вывести топ-5 стран с наименьшей разницей.

Интересно, потому что:

Это позволяет выявить страны, где гендерный разрыв в здоровье особенно заметен, и посмотреть, как он менялся во времени. Может быть полезно для исследований в области здравоохранения и социальной политики.

In [217]:
diff_df = merged_df.pivot_table(index=['CountryCode', 'YearCode'],
                                columns='SexCode',
                                values='Numeric').reset_index()
diff_df['female_male_diff'] = diff_df['FMLE'] - diff_df['MLE']
avg_diff = diff_df.groupby('CountryCode')['female_male_diff'].mean().sort_values(ascending=False)
top5_countries = avg_diff.head()
top5_countries

CountryCode
RUS    9.328148
BLR    8.973347
LTU    8.459569
EST    8.284474
SYC    8.003806
Name: female_male_diff, dtype: float64

In [218]:
top5_countries = avg_diff.tail()
top5_countries

CountryCode
NER    0.149450
KWT    0.063567
MDV    0.039512
QAT   -0.194712
MLI   -0.208137
Name: female_male_diff, dtype: float64

Если посмотреть на разницу в продолжительности жизни женщин и мужчин (female_male_diff), видно, что в некоторых странах она очень большая. В Восточной Европе, например, Россия — 9,3 года, Беларусь — 9,0, Литва — 8,5, Эстония — 8,3, Сейшельские острова — 8,0. А вот в ряде стран Африки и Ближнего Востока разница совсем маленькая или даже отрицательная: Катар — -0,19, Мали — -0,21, Мальдивы — 0,04.

Это говорит о том, что в Восточной Европе нужны специальные программы и меры, которые помогут улучшить мужское здоровье, предупредить хронические болезни и сформировать здоровый образ жизни среди мужчин. В странах, где разница минимальна, подход может быть более универсальным, потому что здоровье мужчин и женщин примерно одинаковое.

## Бонусная часть на анализ целевой переменной (до 5 бонусных баллов)

После всего проделанного анализа и подготовки данных мы можем перейти непосредственно к ответу на исходный вопрос исследования, который был сформулирован вами в задании 3.

### 19

***Бонус (5 бон. баллов):*** Дайте развернутый, обоснованный, подкрепленный данными и написанным вами кодом ответ на вопрос, влияют ли признаки зависимой таблицы на целевую переменную из главной таблицы и, если да, то каким именно образом влияют?

Обязательно аргументируйте полученные вами результаты и выводы. Чем подробнее и обоснованнее анализ вы проведете в рамках данного бонусного задания, тем больше бонусных баллов получите! Вы можете использовать подходы и методы из рассмотренных на семинаре и в рамках данного домашнего задания, а можете придумать и что-то своё. Креативность максимально приветствуется!

Наша цель: проверить, влияет ли уровень потребления алкоголя и другие внешние признаки на ожидаемую продолжительность жизни. Мы будем смотреть на корреляции и усреднённые показатели, чтобы понять направление влияния.

In [219]:
# Сначала создаём новый столбец, который показывает среднее потребление алкоголя на человека по всем видам
alcohol_cols = ['beer_servings', 'spirit_servings', 'wine_servings', 'total_litres_of_pure_alcohol']
merged_df['total_servings'] = merged_df[alcohol_cols].mean(axis=1)
# Считаем корреляции между продолжительностью жизни (Numeric) и всеми видами потребления алкоголя
corrs = merged_df[['Numeric'] + alcohol_cols].corr()['Numeric'].sort_values(ascending=False)
corrs

Numeric                         1.000000
wine_servings                   0.129527
beer_servings                   0.124204
total_litres_of_pure_alcohol    0.112060
spirit_servings                 0.099499
Name: Numeric, dtype: float64

Корреляции получились около 0.1–0.13 — это очень слабая связь, практически незначимая.

Положительные значения говорят о том, что с ростом потребления алкоголя Numeric слегка увеличивается, но эффект минимальный.

Влияние спиртного и пива чуть ниже, чем влияние вина.

В целом, это показывает, что алкоголь не является ключевым фактором, определяющим продолжительность жизни в нашем наборе данных. Вероятно, на неё сильнее влияют другие вещи — доходы, качество здравоохранения, образ жизни, экология и так далее.

То есть эти данные не опровергают потенциальное негативное влияние алкоголя на здоровье, но на уровне агрегированных показателей по странам и годам эффект почти «размазан» и очень слабый.

In [220]:
# Считаем среднюю продолжительность жизни и среднее потребление алкоголя по странам и полу
grouped = merged_df.groupby(['CountryCode','SexCode']).agg({
    'Numeric':'mean',
    'total_litres_of_pure_alcohol':'mean'
}).reset_index()

# Определяем разницу в продолжительности жизни между женщинами и мужчинами в каждой стране
grouped['female_male_diff'] = grouped.groupby('CountryCode')['Numeric'].transform(lambda x: x.max() - x.min())

# Смотрим 10 стран с самой большой разницей
grouped.sort_values('female_male_diff', ascending=False).head(10)

CountryCode SexCode    Numeric  total_litres_of_pure_alcohol  \
442         RUS    FMLE  51.803535                          11.5   
441         RUS    BTSX  47.214438                          11.5   
443         RUS     MLE  42.354646                          11.5   
60          BLR    BTSX  49.315830                          14.4   
61          BLR    FMLE  53.746556                          14.4   
62          BLR     MLE  44.639269                          14.4   
311         LTU     MLE  46.814081                          12.9   
310         LTU    FMLE  55.360884                          12.9   
309         LTU    BTSX  51.319116                          12.9   
165         EST    BTSX  51.849642                           9.5   

     female_male_diff  
442          9.448889  
441          9.448889  
443          9.448889  
60           9.107287  
61           9.107287  
62           9.107287  
311          8.546803  
310          8.546803  
309          8.546803  
165          8.310335

docs:
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.transform.html
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.reset_index.html
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.corr.html
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.pivot_table.html
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.map.html


Если посмотреть на конкретные страны Восточной Европы — Россия, Беларусь, Литва, Эстония — видно, что женщины живут заметно дольше мужчин: разница составляет от 8,3 до 9,4 лет. Например, в России женщины в среднем 51,8 года, мужчины — 42,3–47,2; в Беларуси женщины — 53,7, мужчины — 44,6–49,3.

Уровень потребления алкоголя варьируется, но не коррелирует напрямую с разницей между полами: в России 11,5 литра на человека, в Беларуси 14,4, Литва — 12,9, Эстония — 9,5. Мужчины с более низкой продолжительностью жизни не имеют явно большего потребления алкоголя, чем женщины.

Это указывает на то, что факторы, влияющие на разницу продолжительности жизни между полами, скорее социально-экономические, медицинские и поведенческие, а не просто алкоголь.

Вывод: значительный разрыв между мужчинами и женщинами в этих странах говорит о необходимости внедрения программ и инициатив, направленных на здоровье мужчин и профилактику хронических заболеваний. Алкоголь при этом не выступает главным объясняющим

---

## 📈 Итог исследования

В ходе работы были проанализированы данные по 193 странам.  
Обнаружена слабая отрицательная корреляция между уровнем потребления алкоголя и средней продолжительностью жизни, однако зависимость не является линейной и может зависеть от множества социальных и экономических факторов.

Проект демонстрирует базовые навыки анализа данных: загрузку, очистку, объединение таблиц и визуализацию.

---

## 🚀 Как запустить
Вы можете открыть этот ноутбук в Google Colab:

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/your_username/alcohol-life-expectancy-analysis/blob/main/notebooks/analysis.ipynb)
